= Einleitung <Kapitel2>
Die fortschreitende Digitalisierung führt dazu, dass Organisationen ihre operativen und administrativen Prozesse zunehmend automatisieren, damit Effizienzpotenziale zu nutzen und Wettbewerbs- und Kostendruck zu reagieren. Vor allem Arbeiten, die standardisiert, regelbasiert und wiederkehrend sind, bieten sich für Automatisierungstechnologien an. Robotic Process Automation (RPA) hat sich in diesem Kontext als ein gängiger Ansatz zur Automatisierung digitaler Geschäftsprozesse etabliert @RPAScientificAndIndustrialMapping.
RPA steht für den Einsatz von Software-Robotern, die menschliche Interaktionen mit bestehenden IT-Systemen imitieren, indem sie strukturierte Prozessschritte über grafische Benutzeroberflächen oder definierte Schnittstellen ausführen. Die Technologie wird seit ihrer Entwicklung in den frühen 2000er-Jahren in zahlreiche Sektoren eingesetzt, einschließlich Finanzdienstleistungen, Versicherungen, Industrie und öffentlicher Verwaltung. Firmen erwarten sich von der Verwendung von RPA vor allem eine Verbesserung der Prozessqualität, Effizienzgewinne sowie eine Entlastung der Mitarbeitenden von sich wiederholenden Routinetätigkeiten @RPAScientificAndIndustrialMapping; @EffectsRPA.
Auch die arbeitswissenschaftliche Perspektive gewinnt neben den erwarteten ökonomischen Vorteilen zunehmend an Bedeutung. Nicht nur technische Abläufe werden durch RPA-Einsatz verändert: Auch Arbeitsinhalte, Rollenverteilung sowie das Verständnis von Autonomie und Kontrolle werden beeinflusst. RPA berührt zentrale Fragen der Mensch-Technik-Interaktion in digitalen Arbeitsumgebungen und ist aus betriebswirtschaftlicher sowie organisations- und arbeitswissenschaftlicher Perspektive von großer Bedeutung @Wewerka2020UserAcceptanceRPA.
== Hintergrund und Relevanz <Kapitel2.1>
Die zunehmende Verbreitung von Robotic Process Automation in der Unternehmenspraxis verdeutlicht die Relevanz der Technologie als Instrument zur digitalen Prozessoptimierung. Insbesondere vor dem Hintergrund begrenzter personeller Ressourcen und steigender Anforderungen an Qualität und Geschwindigkeit von Geschäftsprozessen stellt RPA für viele Organisationen einen niedrigschwelligen Einstieg in die Automatisierung dar. Da RPA bestehende IT-Systeme nutzt und keine tiefgreifenden Systemänderungen erfordert, kann die Technologie vergleichsweise schnell implementiert werden @RPAScientificAndIndustrialMapping.
Gleichzeitig gewinnt RPA auch in der wissenschaftlichen Diskussion zunehmend an Bedeutung. Neben der Analyse technischer und wirtschaftlicher Effekte rücken Fragen der nachhaltigen Implementierung, der organisatorischen Einbettung sowie der Auswirkungen auf Mitarbeitende in den Fokus der Forschung. Diese Mehrdimensionalität unterstreicht die Notwendigkeit einer ganzheitlichen Betrachtung der Technologie.
== Problemstellung <Kapitel2.2>
Trotz der zunehmenden praktischen Relevanz von RPA ist bislang unzureichend geklärt, wie sich der Einsatz der Technologie auf unterschiedliche Dimensionen organisationaler Leistungen auswirkt. Währen Effizienzgewinne häufig berichtet werden, zeigen empirische Studien ein heterogenes Bild hinsichtlich der Auswirkungen auf Prozessqualität, Fehlerquoten und Prozessstabilität @EffectsRPA.
Besonders uneinheitlich ist die Befundlage im Hinblick auf die Auswirkungen von RPA auf Mitarbeitende. Einerseits wird RPA als Möglichkeit zur Reduktion monotoner Tätigkeiten und zu Steigerung der Arbeitszufriedenheit beschrieben, andererseits weisen Studien auf Akzeptanzprobleme, Unsicherheiten bezüglich veränderter Rollenprofile sowie potenzielle Belastungseffekte hin @Wewerka2020UserAcceptanceRPA. Zudem fehlen bislang integrierte Untersuchungen, die sowohl objektive Prozesskennzahlen als auch subjektive Wahrnehmungen der Mitarbeitenden berücksichtigen @RPAScientificAndIndustrialMapping.
== Zielsetzung der Arbeit <Kapitel2.3>
Ziel dieser Arbeit ist es, den aktuellen wissenschaftlichen Forschungsstand zu Robotic Prozess Automation systematisch aufzuarbeiten und die Auswirkungen des RPA-Einsatzes auf drei zentrale Dimensionen digitaler Geschäftsprozesse zu analysieren: Prozessqualität, Effizienz und Mitarbeiterzufriedenheit.

Die Arbeit verfolgt einen theoriegeleiteten Ansatz und stützt sich auf etablierte Modelle der Prozessbewertung, Motivationstheorie sowie Technologieakzeptanzforschung. Durch die systematische Analyse und Synthese bestehender Studien sollen zentrale Wirkungszusammenhänge identifiziert, widersprüchliche Befunde eingeordnet und bestehende Forschungslücken aufgezeigt werden, aufbauend darauf werden praxisorientierte Handlungsempfehlungen für eine erfolgreiche und mitarbeiterorientierte Einführung von RPA abgeleitet @Nielsen2023RPABenefits.
== Forschungsfrage <Kapitel2.4>
Aus der dargestellten Problemstellung und Zielsetzung ergibt sich folgende Forschungsfrage:

Wie wirkt sich der Einsatz von Robotic Process Automation (RPA) auf die Prozessqualität, Effizienz und Mitarbeiterzufriedenheit in digitalen Geschäftsprozessen aus?
== Aufbau der Arbeit <Kapitel2.5>
Die Arbeit gliedert sich wie folgt:
In (@Kapitel3) stellt die theoretischen Grundlagen und relevanten Modelle zu Robotic Process Automation, Prozessqualität, Effizienz und Technologieakzeptanz dar.
In (@Kapitel4) gibt einen systematischen Überblick über den Stand der Forschung und identifiziert bestehende Forschungslücken.
In (@Kapitel5) beschreibt das methodische Vorgehen der systematischen Literaturrecherche.
In (@Kapitel6) werden die Auswirkungen von RPA auf die untersuchten Dimensionen analysiert.
In (@Kapitel7) diskutiert die Ergebnisse im theoretischen Kontext.
In (@Kapitel8) leitet praxisorientierte Handlungsempfehlungen ab.
In (@Kapitel9) schließt dann die Arbeit mit einem Fazit inkl. Ausblick ab.

= Grundlagen und theoretischer Rahmen <Kapitel3>
== Robotic Process Automation (RPA) — Definition und Funktionsweise <Kapitel3.1>
Robotic Process Automation bezeichnet den Einsatz von Software-Robotern zur Automatisierung strukturierter, regelbasierter Geschäftsprozesse in bestehenden IT-Systemlandschaften. Die Software-Roboter imitieren menschliche Interaktionen, indem sie Prozessschritte über grafische Benutzeroberflächen oder definierte Schnittstellen ausführen @RPAScientificAndIndustrialMapping.
Ein wesentliches Merkmal von RPA ist die nicht-invasive Implementierung. Bestehende IT-Systeme müssen nicht verändert werden, wodurch sich RPA insbesondere für heterogene Systemlandschaften eignet. Typische Anwendungsfälle sind die Übertragung von Daten zwischen Systemen, die Verarbeitung strukturierter Dokumente sowie standardisierte Prüf- und Abgleichsprozesse @RPAScientificAndIndustrialMapping.
Die Funktionsweise von RPA basiert auf explizit modellierten Regeln und Ablaufdefinitionen, die deterministisch ausgeführt werden. Dadurch lassen sich Prozessschritte reproduzierbar und skalierbar automatisieren. Der tatsächliche Nutzen von RPA hängt jedoch maßgeblich von der Prozessreife, dem Automatisierungsgrad sowie dem Umgang mit Ausnahmen ab @EffectsRPA.
Neben technischen Aspekten beeinflusst der Einsatz von RPA auch organisatorische Strukturen. Da Software-Roboter Tätigkeiten übernehmen, die zuvor von Mitarbeitenden ausgeführt wurden, verändern sich Aufgabenverteilungen und Rollenprofile. Diese Veränderungen sind hauptsächlich im Hinblick auf Mitarbeiterzufriedenheit und Technologieakzeptanz von Bedeutung @Wewerka2020UserAcceptanceRPA.
== Abgrenzung zu BPM, Workflow-Automation und KI <Kapitel3.2>
Zur theoretischen Einordnung von Robotic Process Automation ist eine Abgrenzung zu verwandten Automatisierungskonzepten erforderlich. Business Process Management (BPM) verfolgt einen ganzheitlichen Ansatz zur Analyse, Gestaltung und kontinuierlichen Verbesserung von Geschäftsprozessen. RPA kann in diesem Kontext als operatives Werkzeug verstanden werden, das einzelne Prozessschritte automatisiert, ohne notwendigerweise eine umfassende Prozessneugestaltung vorauszusetzen @RPAScientificAndIndustrialMapping.
Workflow-Automation basiert typischerweise auf systeminternen Prozess-Engines und erfordert eine enge Integration der beteiligten IT-Systeme. Im Vergleich dazu zeichnet sich RPA durch eine geringere technische Einstiegshürde aus, ist jedoch stärker von stabilen Benutzeroberflächen und klar definierten Regeln abhängig.
KI-basierte Automatisierungslösungen erweitern klassische RPA-Ansätze um adaptive Fähigkeiten wie Mustererkennung oder maschinelles Lernen. Während klassische RPA deterministisch arbeitet, ermöglichen KI-Komponenten die Verarbeitung unstrukturierter Daten. In der Praxis stellt RPA häufig die Grundlage für weiterführende Automatisierungsinitiativen dar @Nielsen2023RPABenefits.
Für die vorliegende Arbeit liegt der Fokus bewusst auf klassischer RPA, um deren Auswirkungen auf Prozessqualität, Effizienz und Mitarbeitende klar abgrenzen zu können.
== Prozessqualität — Modelle, Kriterien und Messgrößen <Kapitel3.3>
Prozessqualität beschreibt den Grad, zu dem ein Geschäftsprozess definierte Anforderungen zuverlässig, fehlerarm und stabil erfüllt. In der wissenschaftlichen Literatur zu Robotic Process Automation wird Prozessqualität häufig als zentrale Zielgröße von Automatisierungsinitiativen betrachtet, insbesondere im Hinblick auf Konsistenz und Reproduzierbarkeit von Prozessabläufen @RPAScientificAndIndustrialMapping.
Zur konzeptionellen Einordnung wird Prozessqualität meist als mehrdimensionale Größe verstanden, die sowohl die Art der Prozessdurchführung als auch das erzielte Ergebnis berücksichtigt. Im Kontext digitaler Geschäftsprozesse stehen dabei insbesondere stabile Abläufe, geringe Fehleranfälligkeit sowie die Einhaltung definierter Servicelevel im Vordergrund @EffectsRPA.
Die Operationalisierung von Prozessqualität erfolgt in der Regel über quantitative Kennzahlen. Häufig verwendete Messgrößen sind unter anderem Fehlerquoten, Nachbearbeitungsraten, Prozessabbrüche sowie Servicelevel-Indikatoren. Diese Kennzahlen ermöglichen eine vergleichende Bewertung von Prozessleistungen vor und nach der Einführung von Automatisierungsmaßnahmen @EffectsRPA.
Im Zusammenhang mit Robotic Process Automation wird Prozessqualität häufig mit der Annahme verknüpft, dass automatisierte Prozessschritte konsistenter ausgeführt werden als manuelle Tätigkeiten. Empirische Untersuchungen zeigen jedoch, dass Qualitätseffekte stark von der Prozessgestaltung, der Regeldefinition sowie dem Umgang mit Ausnahmen abhängen. Fehlkonfigurationen oder unzureichend modellierte Sonderfälle können neue Fehlerquellen erzeugen und die Prozessqualität negativ beeinflussen @RPAScientificAndIndustrialMapping.
Für die vorliegende Arbeit dient Prozessqualität als zentrale Analyseperspektive zur Bewertung der Auswirkungen von RPA auf digitale Geschäftsprozesse. Die dargestellten Konzepte und Messgrößen bilden die theoretische Grundlage für die spätere Analyse von Fehlerquoten, Prozessstabilität und Servicequalität in (@Kapitel6).
== Effizienz — Durchlaufzeiten, Ressourceneinsatz, Kennzahlen <Kapitel3.4>
Effizienz beschreibt das Verhältnis zwischen eingesetzten Ressourcen und erzielten Prozessergebnissen und stellt eine zentrale Zielgröße im Kontext der Prozessautomatisierung dar. In digitalen Geschäftsprozessen wird Effizienz insbesondere über Zeit-, Kosten- und Kapazitätsaspekte operationalisiert. Ziel ist es, Prozesse schneller, mit geringerem Ressourceneinsatz und bei gleichbleibender oder verbesserter Qualität durchzuführen.
Zur Bewertung von Effizienz werden in der Forschung und Praxis überwiegend quantitative Kennzahlen herangezogen. Zu den wichtigsten Messgrößen zählen Durchlaufzeiten, Bearbeitungszeiten, Automatisierungsgrade sowie der personelle und technische Ressourceneinsatz. Diese Kennzahlen ermöglichen eine objektive Bewertung von Prozesseffekten und dienen als Grundlage für Vorher-Nachher-Vergleiche bei der Einführung von Automatisierungstechnologien @EffectsRPA.
Im Zusammenhang mit Robotic Process Automation wird Effizienz häufig als primärer Nutzenfaktor beschrieben. Software-Roboter können Prozessschritte kontinuierlich, mit gleichbleibender Geschwindigkeit und ohne Pausen ausführen, wodurch primär in transaktionsreichen Prozessen signifikante Zeitgewinne erzielt werden können. Empirische Studien zeigen, dass sich durch RPA sowohl Durchlaufzeiten als auch Bearbeitungszeiten deutlich reduzieren lassen, insbesondere bei hohem Standardisierungsgrad der Prozesse @EffectsRPA.
Neben zeitlichen Effekten beeinflusst RPA auch den Ressourceneinsatz. Durch die Automatisierung manueller Tätigkeiten können personelle Kapazitäten freigesetzt und auf höherwertige Aufgaben verlagert werden. Gleichzeitig entstehen neue Aufwände für Entwicklung, Betrieb und Wartung der Software-Roboter, die bei der Effizienzbewertung berücksichtigt werden müssen. Effizienzgewinne sind daher nicht ausschließlich kurzfristig zu betrachten, sondern im Kontext des gesamten Lebenszyklus von RPA-Initiativen zu bewerten @Nielsen2023RPABenefits.
Für die vorliegende Arbeit dient Effizienz als zweite zentrale Analyseperspektive zur Bewertung der Auswirkungen von RPA. Die dargestellten Kennzahlen und Konzepte bilden die theoretische Grundlage für die Analyse von Zeit-, Kosten- und Skalierungseffekten in (@Kapitel6.2).
== Mitarbeiterzufriedenheit — Motivationstheorien und Belastungsmodelle <Kapitel3.5>
Mitarbeiterzufriedenheit beschreibt den Grad, zu dem Mitarbeitende ihre Arbeitssituation positiv bewerten und stellt eine zentrale Einflussgröße für Motivation, Leistungsbereitschaft und Akzeptanz organisationaler Veränderungen dar. Im Kontext digitaler Transformation gewinnt diese Perspektive insbesondere bei der Einführung von Automatisierungstechnologien an Bedeutung, da diese bestehende Arbeitsabläufe und Rollenprofile verändern.
Theoretisch lässt sich Mitarbeiterzufriedenheit unter anderem durch motivationstheoretische Ansätze erklären, die zwischen intrinsischen und extrinsischen Motivationsfaktoren unterscheiden. Tätigkeiten, die als monoton, repetitiv oder wenig sinnstiftend wahrgenommen werden, wirken sich häufig negativ auf Motivation und Zufriedenheit aus. Automatisierungstechnologien wie RPA werden daher oft mit der Erwartung verbunden, Mitarbeitende von solchen Routinetätigkeiten zu entlasten und ihnen anspruchsvollere Aufgaben zu ermöglichen @Wewerka2020UserAcceptanceRPA.
Gleichzeitig weisen arbeitswissenschaftliche Modelle darauf hin, dass technologische Veränderungen auch neue Belastungen erzeugen können. Dazu zählen unter anderem Unsicherheiten hinsichtlich veränderter Rollen, erhöhte Kontrollwahrnehmung oder zusätzliche Anforderungen durch Überwachung und Ausnahmebearbeitung. Ob sich RPA positiv oder negativ auf die Mitarbeiterzufriedenheit auswirkt, hängt daher stark von der konkreten Gestaltung der Technologieeinführung sowie von begleitenden organisatorischen Maßnahmen ab @Wewerka2020UserAcceptanceRPA.
Empirische Studien zeigen, dass die Akzeptanz von RPA eng mit der wahrgenommenen Nützlichkeit, der Transparenz der Einführung sowie der Einbindung der Mitarbeitenden in den Veränderungsprozess verknüpft ist. Werden Software-Roboter als unterstützendes Werkzeug wahrgenommen, kann dies zu einer Steigerung der Arbeitszufriedenheit führen. Fehlt hingegen eine klare Kommunikation oder Partizipation, können Widerstände und Belastungseffekte entstehen @Wewerka2020UserAcceptanceRPA.
Für die vorliegende Arbeit stellt Mitarbeiterzufriedenheit die dritte zentrale Analyseperspektive dar. Die dargestellten theoretischen Ansätze bilden die Grundlage für die spätere Analyse der Auswirkungen von RPA auf Motivation, Belastung und Akzeptanz von Mitarbeitenden in digitalen Geschäftsprozessen.
== Technologieakzeptanz — TAM, UTAUT und Change-Management <Kapitel3.6>
Die Akzeptanz neuer Technologien durch Mitarbeitende stellt einen zentralen Erfolgsfaktor für Digitalisierungs- und Automatisierungsinitiativen dar. Insbesondere bei der Einführung von Robotic Process Automation beeinflusst die Wahrnehmung der Technologie maßgeblich, ob die angestrebten Effizienz- und Qualitätsziele tatsächlich realisiert werden können. Technologieakzeptanz beschreibt dabei die Bereitschaft von Nutzenden, eine Technologie anzunehmen, zu verwenden und dauerhaft in Arbeitsprozesse zu integrieren.
In der Forschung zur Technologieakzeptanz haben sich verschiedene theoretische Modelle etabliert. Zentrale Annahmen dieser Modelle besagen, dass die Nutzung neuer Technologien vor allem von der wahrgenommenen Nützlichkeit sowie der wahrgenommenen Benutzerfreundlichkeit abhängt. Im Kontext von RPA bedeutet dies, dass Software-Roboter von Mitarbeitenden als unterstützend und nicht als zusätzliche Belastung wahrgenommen werden müssen, um Akzeptanz zu erzeugen @Wewerka2020UserAcceptanceRPA.
Erweiterte Akzeptanzmodelle berücksichtigen darüber hinaus soziale und organisationale Einflussfaktoren, etwa die Unterstützung durch Führungskräfte, organisatorische Rahmenbedingungen oder vorhandene Kompetenzen. Studien im RPA-Kontext zeigen, dass Transparenz, Schulung und frühzeitige Einbindung der Mitarbeitenden entscheidend für eine positive Akzeptanzentwicklung sind @Wewerka2020UserAcceptanceRPA.
Neben individuellen Akzeptanzfaktoren spielt auch das Change-Management eine zentrale Rolle bei der Einführung von RPA. Da Automatisierung häufig mit Veränderungen von Aufgaben, Verantwortlichkeiten und Arbeitsabläufen einhergeht, sind begleitende Maßnahmen erforderlich, um Unsicherheiten zu reduzieren und Widerstände zu vermeiden. Ein strukturiertes Change-Management kann dazu beitragen, RPA als unterstützende Technologie zu positionieren und die langfristige Nutzung sicherzustellen @Nielsen2023RPABenefits.
Für die vorliegende Arbeit bildet die Technologieakzeptanz einen wichtigen theoretischen Bezugsrahmen, um die Auswirkungen von RPA auf Mitarbeitende zu erklären. Die dargestellten Konzepte ermöglichen es, Akzeptanz- und Widerstandseffekte systematisch zu analysieren und im späteren Verlauf der Arbeit in Beziehung zu Prozessqualität und Effizienz zu setzen.

= Stand der Forschung <Kapitel4>
== Systematische Übersicht der Literatur zu RPA <Kapitel4.1>
Die wissenschaftliche Auseinandersetzung mit Robotic Process Automation hat in den vergangenen Jahren deutlich zugenommen, parallel zur wachsenden praktischen Verbreitung der Technologie. Ein Großteil der bestehenden Forschung beschäftigt sich mit der konzeptionellen Einordnung von RPA, der Beschreibung von Einsatzszenarien sowie der Analyse potenziellen Nutzen- und Risikoaspekte. Systematische Übersichtsarbeiten zeigen, dass RPA insbesondere in stark standardisierten, transaktionsorientierten Geschäftsprozessen eingesetzt wird @RPAScientificAndIndustrialMapping.
Die Literatur zu RPA lässt sich grob in drei thematische Schwerpunkte unterteilen: Erstens fokussieren zahlreiche Studien auf technologische und prozessuale Aspekte, etwa die Funktionsweise von RPA, typische Einsatzbereiche sowie Implementierungsansätze. Zweitens befassen sich empirische Arbeiten mit den Auswirkungen von RPA auf Effizienz und Prozessleistung, wobei  insbesondere Zeitersparnisse, Kosteneffekte und Automatisierungsgrade analysiert werden @EffectsRPA. Drittens rückt zunehmend die Mitarbeiterperspektive in den Fokus, häufig im Hinblick auf Akzeptanz, Rollenveränderungen und arbeitsbezogene Auswirkungen @Wewerka2020UserAcceptanceRPA.
Methodisch dominieren in der RPA-Forschung qualitative Fallstudien, konzeptionelle Arbeiten sowie vereinzelt quantitative Analysen. Während Fallstudien detaillierte Einblicke in konkrete Anwendungskontexte liefern, sind vergleichende quantitative Untersuchungen bislang seltener. Hauptsächlich Studien, die objektive Prozesskennzahlen mit subjektiven Wahrnehmungen von Mitarbeitenden kombinieren, sind bislang unterrepräsentiert @RPAScientificAndIndustrialMapping.
Darüber hinaus zeigt die Literatur, dass Effekte von RPA stark vom jeweiligen Anwendungskontext abhängen. Faktoren wie Prozessreife, Standardisierungsgrad, organisatorische Einbettung und begleitende Change-Management-Maßnahmen beeinflussen maßgeblich, ob RPA positive Auswirkungen auf Effizienz und Qualität entfalten kann @Nielsen2023RPABenefits. Eine isolierte Betrachtung der Technologie ohne Berücksichtigung dieser Kontextfaktoren greift daher häufig zu kurz.
Zusammenfassend lässt sich festhalten, dass die bestehende Forschung wertvolle Erkenntnisse zu Einsatzmöglichkeiten und Potenzialen von RPA liefert, jedoch bislang kein einheitliches Bild hinsichtlich der Wirkung auf Prozessqualität, Effizienz und Mitarbeiterzufriedenheit zeichnet. Diese Heterogenität der Befunde bildet die Grundlage für die nachfolgenden Kapitel, in denen die empirischen Ergebnisse entlang der drei Untersuchungsdimensionen systematisch aufgearbeitet werden.
== Befunde zur Prozessqualität <Kapitel4.2>
Die Auswirkungen von Robotic Process Automation auf die Prozessqualität werden in der bestehenden Literatur überwiegend positiv bewertet, jedoch zeigen empirische Studien ein differenziertes und teilweise widersprüchliches Bild. Prozessqualität wird dabei vor allem anhand von Kriterien wie Fehlerquoten, Prozessstabilität und Servicelevel analysiert. RPA wird häufig mit der Erwartung verbunden, dass automatisierte Prozessschritte konsistenter und weniger fehleranfällig ausgeführt werden als manuelle Tätigkeiten @RPAScientificAndIndustrialMapping.
Empirische Untersuchungen berichten, insbesondere von einer Reduktion manueller Eingabefehler sowie einer erhöhten Reproduzierbarkeit von Prozessabläufen. Da Software-Roboter deterministisch arbeiten und definierte Regeln strikt einhalten, lassen sich Abweichungen durch menschliche Ermüdung oder Unaufmerksamkeit vermeiden. Diese Effekte treten vor allem in stark standardisierten und strukturierten Prozessen auf @EffectsRPA.
Gleichzeitig weisen Studien darauf hin, dass der Einsatz von RPA neue Risiken für die Prozessqualität mit sich bringen kann. Fehlerhafte Regeldefinitionen, unzureichend modellierte Ausnahmefälle oder Änderung an Benutzeroberflächen können dazu führen, dass automatisierte Prozesse fehlerhaft oder instabil ausgeführt werden. In solchen Fällen kann sich die Prozessqualität trotz Automatisierung sogar verschlechtern @RPAScientificAndIndustrialMapping.
Darüber hinaus zeigen empirische Befunde, dass Qualitiätseffekte von RPA stark vom organisatorischen Kontext abhängen. Prozesse mit hoher Variabilität oder einem hohen Anteil unstrukturierter Daten profitieren deutlich weniger von RPA als klar definierte Routinetätigkeiten. Auch fehlende Governance-Strukturen und unzureichendes Monitoring können dazu beitragen, dass potenzielle Qualitätsgewinne nicht realisiert werden @Nielsen2023RPABenefits.
Zusammenfassend lässt sich festhalten, dass RPA das Potenzial hat, die Prozessqualität in digitalen Geschäftsprozessen zu verbessern, diese Effekte jedoch nicht automatisch eintreten. Vielmehr sind sie an Voraussetzungen wie geeignete Prozessauswahl, sorgfältige Modellierung und kontinuierliche Überwachung geknüpft. Diese Erkenntnisse unterstreichen die Notwendigkeit einer differenzierten Bewertung der Technologie, die in den nachfolgenden Kapiteln weiter vertieft wird.
== Befunde zur Effizienzsteigerung <Kapitel4.3>
Die Effizienzsteigerung zählt zu den am häufigsten genannten Zielsetzungen beim Einsatz von Robotic Process Automation und stellt einen zentralen Fokus der empirischen RPA-Forschung dar. Effizienz wird dabei überwiegend anhand von Kennzahlen wie Durchlaufzeiten, Bearbeitungszeiten, Automatisierungsgrad sowie Kosten- und Ressourceneffekten bewertet @EffectsRPA.
Empirische Studien zeigen, dass der Einsatz von RPA insbesondere in stark standardisierten und transaktionslastigen Prozessen zu signifikanten Zeitersparnissen führen kann. Software-Roboter arbeiten kontinuierlich, mit gleichbleibender Geschwindigkeit und ohne Pausen, woduruch sich Durchlauf- und Bearbeitungszeiten deutlich reduzieren lassen. Diese Effekte sind vor allem in Supportprozessen wie Rechnungsverarbeitung, Stammdatenpflege oder Reporting zu beobachten @EffectsRPA.
Neben zeitlichen Effekten berichten Studien auch von positiven Auswirkungen auf den Ressourceneinsatz. Durch die Automatisierung manueller Routinetätigkeiten können personelle Kapazitäten freigesetzt und für komplexere oder wertschöpfende Aufgaben eingesetzt werden. Gleichzeitig zeigen Untersuchungen, dass Effizienzgewinne nicht ausschließlich durch Personaleinsparungen entstehen, sondern auch durch verbesserte Skalierbarkeit und höhere Prozessstabilität @Nielsen2023RPABenefits.
Allerdings weisen empirische Befunde darauf hin, dass Effizienzgewinne durch RPA stark kontextabhängig sind. Prozesse mit hoher Variabilität, häufig Ausnahmen oder unzureichender Standardisierung profitieren deutlich weniger von RPA. Zudem entstehen zusätzliche Aufwände für Entwicklung, Betrieb und Wartung der Software-Roboter, die oft bei langfristiger Betrachtung berücksichtigt werden müssen @RPAScientificAndIndustrialMapping.
Zusammenfassend lässt sich festhalten, dass RPA ein hohes Potenzial zur Effizienzsteigerung bietet, diese Effekte jedoch nicht automatisch eintreten. Vielmehr hängen sie von der geeigneten Prozessauswahl, dem Automatisierungsgrad sowie der organisatorischen Einbettung der Technologie ab. Diese differenzierte Befundlage bildet die Grundlage für die weitere Analyse der Effizienzdimension in (@Kapitel6.2).
== Befunde zur Mitarbeiterzufriedenheit <Kapitel4.4>
Die Auswirkungen von Robotic Process Automation auf die Mitarbeiterzufriedenheit werden in der bestehenden Forschung deutlich ambivalenter bewertet als Effekte auf Prozessqualität oder Effizienz. Während RPA häufig mit der Erwartung verbunden ist, Mitarbeitende von monotonen oder repetitiven Tätigkeiten zu entlasten, zeigen empirische Studien ein differenziertes Bild hinsichtlich Motivation, Belastung und Akzeptanz @Wewerka2020UserAcceptanceRPA.
Ein Teil der Literatur berichtet von positiven Effekten auf die Arbeitszufriedenheit, insbesondere wenn RPA dazu beiträgt, routinemäßige Tätigkeiten zu reduzieren und Mitarbeitende mehr Zeit für anspruchsvollere Aufgaben zu verschaffen. In solchen Fällen wird RPA als unterstützende Technologie wahrgenommen, die Autonomie und wahrgenommene Nützlichkeit der Arbeit erhöhen kann @Wewerka2020UserAcceptanceRPA.
Demgegenüber weisen andere Studien auf potenzielle negative Effekte hin. Dazu zählen Unsicherheiten im Hinblick auf veränderte Rollenprofile, Befürchtungen hinsichtlich Arbeitsplatzsicherheit sowie eine erhöhte Belastung durch Überwachung oder die Bearbeitung von Ausnahmefällen, die nicht automatisiert werden können. Insbesondere bei fehlender Transparenz und unzureichender Kommunikation im Einführungsprozess kann RPA als Bedrohung wahrgenommen werden @Wewerka2020UserAcceptanceRPA.
Empirische Befunde zeigen zudem, dass die Akzeptanz von RPA stark von organisationalen Rahmenbedingungen abhängt. Eine frühzeitige Einbindung der Mitarbeitenden, klare Kommunikation der Ziele sowie Schulungs- und Qualifizierungsmaßnahmen wirken sich positiv auf die Wahrnehmung und Nutzung der Technologie aus. Fehlen diese begleitenden Maßnahmen, steigt die Wahrscheinlichkeit von Widerständen und Akzeptanzproblemen @RPAScientificAndIndustrialMapping.
Zusammenfassend lässt sich festhalten, dass RPA weder per se zu einer Steigerung noch zu einer Reduktion der Mitarbeiterzufriedenheit führt. Vielmehr hängen die arbeitsbezogenen Effekte maßgeblich von der konkreten Gestaltung der RPA-Einführung, dem organisationalen Kontext sowie der Rolle der Mitarbeitenden im automatisierten Prozess ab. Diese Befunde unterstreichen die Bedeutung einer mitarbeiterorientierten Implementationsstrategie, die in den folgenden Kapiteln weiter aufgegriffen wird.
== Forschungslücken und offene Fragen <Kapitel4.5>
Die Analyse des bisherigen Forschungsstands zeigt, dass Robotic Process Automation in der Literatur bereits umfassend beschrieben wird, jedoch weiterhin wesentliche Forschungslücken bestehen. Insbesondere mangelt es an einer integrierten Betrachtung der Auswirkungen von RPA auf Prozessqualität, Effizienz und Mitarbeiterzufriedenheit. Viele Studien fokussieren sich isoliert auf einzelne Dimensionen, wodurch ein ganzheitliches Verständnis der Wirkungszusammenhänge erschwert wird @RPAScientificAndIndustrialMapping.
Eine Zentrale Forschungslücke besteht in der begrenzten Anzahl an empirischer Studien, die objektive Prozesskennzahlen mit subjektiven Wahrnehmungen der Mitarbeitenden kombinieren. Während Effizienzgewinne häufig anhand quantitativer Metriken untersucht werden, bleiben arbeitsbezogene Effekte wie Motivation, Akzeptanz oder wahrgenommene Belastung oft unterbelichtet oder werden lediglich qualitativ erfasst @EffectsRPA; @Wewerka2020UserAcceptanceRPA.
Darüber hinaus weisen bestehende Untersuchungen eine starke Kontextabhängigkeit auf. Effekte von RPA variieren erheblich in Abhängigkeit von Prozessart, Automatisierungsgrad und organisationalen Rahmenbedingungen. Insbesondere Unterschiede zwischen operativen Kernprozessen und unterstützenden Supportprozessen werden bislang nur unzureichend systematisch analysiert @Nielsen2023RPABenefits.
Ein weiteres Defizit liegt in der begrenzten theoretischen Fundierung vieler empirischer Arbeiten. Obwohl Konzepte wie Technologieakzeptanz und Motivation vereinzelt herangezogen werden, fehlt häufig eine konsistente theoretische Integration, um die beobachteten Effekte von RPA auf Mitarbeitende und Prozesse zu erklären @Wewerka2020UserAcceptanceRPA. Dies erschwert sowohl die Vergleichbarkeit bestehender Studien als auch die Ableitung generalisierbarer Handlungsempfehlungen.
Zusammenfassend besteht ein Bedarf an theoriegeleiteten Untersuchungen, die die Auswirkungen von RPA multidimensional erfassen und sowohl technische als auch menschliche Aspekte berücksichtigen. An dieser Stelle setzt die vorliegende Arbeit an, indem sie bestehende empirische Befunde systematisch synthetisiert und entlang der Dimensionen Prozessqualität, Effizienz und Mitarbeiterzufriedenheit analysiert.
== Zusammenfassung des Forschungsstands <Kapitel4.6>
Der Überblick über den bisherigen Forschungsstand zeigt, dass Robotic Process Automation ein intensiv untersuchtes und zugleich dynamisches Forschungsfeld darstellt. Die vorhandene Literatur liefert wertvolle Erkenntnisse zu Einsatzmöglichkeiten, Potenzialen und Herausforderungen der Technologien, insbesondere im Hinblick auf Effizienzsteigerungen und die Automatisierung standardisierter Geschäftsprozesse @RPAScientificAndIndustrialMapping; @EffectsRPA.
Gleichzeitig verdeutlichen die empirischen Befunde, dass die Auswirkungen von RPA auf Prozessqualität, Effizienz und Mitarbeiterzufriedenheit nicht eindeutig und teilweise widersprüchlich sind. Während Effizienzgewinne in vielen Studien nachgewiesen werden, hängen Effekte auf Prozessqualität und arbeitsbezogene Faktoren stark vom jeweiligen Anwendungskontext, der Prozessgestaltung sowie der organisationalen Einbettung ab @EffectsRPA; @Wewerka2020UserAcceptanceRPA.
Häufig zeigt sich, dass Mitarbeiterzufriedenheit und Technologieakzeptanz eine zentrale Rolle für den Erfolg von RPA-Initativen spiele. Ohne geeignete begleitende Maßnahmen wie transparente Kommunikation, Schulung und Einbindung der Mitarbeitenden können potenzielle Effizienz- und Qualitätsgewinne nicht vollständig realisiert werden @Wewerka2020UserAcceptanceRPA.
Zusammenfassend lässt sich festhalten, dass trotz wachsender Literatur weiterhin ein Bedarf an integrierten, theoriegeleiteten Analysen besteht, die technische Prozesskennzahlen und menschliche Faktoren gemeinsam betrachten. Diese Erkenntnis bildet die Grundlage für das methodische Vorgehen der vorliegenden Arbeit, das im folgenden Kapitel beschrieben wird.

= Methodik<Kapitel5>
== Forschungsdesign <Kapitel5.1>
Die vorliegende Arbeit verfolgt ein theoriegeleitetes, qualitatives Forschungsdesign in Form einer systematischen Literaturarbeit. Ziel ist es, bestehende wissenschaftliche Erkenntnisse zum Einsatz von Robotic Process Automation (RPA) zu analysieren, zu strukturieren und entlang der drei zentralen Untersuchungsdimensionen Prozessqualität, Effizienz und Mitarbeiterzufriedenheit zu synthetisieren.
Ein Literatur-basiertes Forschungsdesign eignet sich insbesondere für Fragestellungen, bei denen ein breiter Überblick über den aktuellen Stand der Forschung erforderlich ist und empirische Befunde bislang heterogen oder widersprüchlich vorliegen. Da RPA ein vergleichsweise junges, jedoch dynamisch wachsendes Forschungsfeld darstellt, ermöglicht die systematische Auswertung vorhandener Studien eine fundierte Einordnung bestehender Ergebnisse sowie die Identifikation von Forschungslücken.
Die Arbeit folgt einem deduktiv-analytischen Vorgehen. Aufbauend auf etablierten theoretischen Konzepten aus dem Prozessmanagement, der Effizienzforschung sowie der Technologieakzeptanz werden relevante Studien ausgewählt und inhaltlich analysiert. Die theoretischen Modelle dienen dabei als analytischer Rahmen zur Strukturierung und Interpretation der empirischen Befunde.
Auf eine eigene empirische Datenerhebung wird bewusst verzichtet. Stattdessen liegt der Fokus auf der systematischen Synthese bestehender empirischer Arbeiten, um übergreifende Muster, Zusammenhänge und Unterschiede zwischen verschiedenen Anwendungskontexten von RPA herauszuarbeiten. Dieses Vorgehen ermöglicht es, sowohl technische als auch arbeitsbezogene Effekte der Technologie integriert zu betrachten.
Das gewählte Forschungsdesign bildet die Grundlage für die im folgenden Kapitel beschrieben systematische Literaturrecherche. Dort werden das konkrete Vorgehen, die Suchstrategie sowie die Auswahl- und Ausschlusskriterien detailliert dargestellt.
== Systematische Literaturrecherche — Vorgehen und Suchstrategie <Kapitel5.2>
Zur Beantwortung der Forschungsfrage wurde eine systematische Literaturrecherche durchgeführt. Ziel der Recherche war es, relevante wissenschaftliche Publikationen zum Einsatz von Robotic Process Automation (RPA) zu identifizieren, die empirische Aussagen zu den Auswirkungen auf Prozessqualität, Effizienz und Mitarbeiterzufriedenheit enthalten.
Die Literaturrecherche erfolgte in der wissenschaftlichen Datenbank IEEE Xplore, da diese eine zentrale Quelle für qualitativ hochwertige Publikationen im Bereich der Informationssysteme, Prozessautomatisierung und Digitalisierung darstellt. Ergänzend wurden Literaturverzeichnisse einschlägiger Übersichtsarbeiten herangezogen, um relevante Studien zu identifizieren, die im Rahmen der Datenbanksuche möglicherweise nicht erfasst wurden (Backward Snowballing) @RPAScientificAndIndustrialMapping.
Die Suchstrategie basierte auf einer Kombination themenspezifischer Suchbegriffe. Zentrale Suchbegriffe waren unter anderem: "Robotic Process Automation", "RPA", "process quality", "efficiency", "employee satisfaction", "technology acceptance". Diese Begriffe wurden sowohl einzeln als auch in Kombination verwendet, um eine möglichst umfassende Abdeckung des Forschungsfeldes zu gewährleisten.
Um die Relevanz und Aktualität der identifizierten Literatur sicherzustellen, wurde der Suchzeitraum auf Publikation der letzten Jahre fokussiert, wobei grundlegende Arbeiten mit hoher Zitierhäufigkeit ergänzend berücksichtigt wurden. Die initiale Trefferliste wurde anschließend anhand definierter Auswahl- und Ausschlusskriterien in (@Kapitel5.3) weiter eingegrenzt.
Die identifizierten Studien wurden systematisch gesichtet und inhaltlich analysiert. Dabei wurden zentrale Aussagen, verwendeter Methoden sowie untersuchte Wirkungsdimensionen extrahiert und für die weitere Analyse strukturiert. Dieses Vorgehen stellt sicher, dass die Literaturauswahl nachvollziehbar, reproduzierbar und inhaltlich konsistent ist.
== Auswahl- und Ausschlusskriterien <Kapitel5.3>
Um die Qualität und Relevanz der in die Analyse einbezogenen Studien sicherzustellen, wurden im Rahmen der systematischen Literaturrecherche klare Auswahl- und Ausschlusskriterien definiert. Diese Kriterien dienten dazu, die initial identifizierte Literatur gezielt einzugrenzen und nur solche Publikationen zu berücksichtigen, die einen substantiellen Beitrag zur Beantwortung der Forschungsfrage leisten.
Als Einschlusskriterien galten wissenschaftliche Publikationen, die sich explizit mit Robotic Process Automation befassen und empirische oder konzeptionelle Aussagen zu mindestens einer der drei Untersuchungsdimensionen Prozessqualität, Effizienz oder Mitarbeiterzufriedenheit enthalten. Zudem wurden ausschließlich Veröffentlichungen berücksichtigt, die in peer-reviewten IEEE-Publikationen erschienen sind, um eine hohe wissenschaftliche Qualität sicherzustellen. Der Fokus lag dabei auf Artikeln und Konferenzbeiträgen in englischer Sprache.
Zu den Ausschlusskriterien zählten Arbeiten, die sich lediglich randständig mit RPA befassen oder den Begriff unspezifisch im Kontext allgemeiner Automatisierung verwenden. Ebenfalls ausgeschlossen wurden Studien ohne erkennbaren Bezug zu Geschäftsprozessen oder ohne analytische Auseinandersetzung mit den Auswirkungen von RPA. Nicht-wissenschaftliche Publikationen, Praxisberichte ohne methodische Fundierung sowie Duplikate wurde ebenfalls nicht berücksichtigt.
Die Anwendung der Auswahl- und Ausschlusskriterien erfolgte in mehreren Schritten. Zunächst wurden Titel und Abstracts gesichtet, um offensichtliche irrelevante Arbeiten auszuschließen. Anschließend erfolgte eine Volltextprüfung der verbleibenden Studien. Dieses mehrstufige Vorgehen gewährleistet ein transparente und nachvollziehbare Literaturauswahl und bildet die Grundlage für die anschließende inhaltliche Analyse.
== Analysekategorien: Prozessqualität, Effizienz, Mitarbeitende <Kapitel5.4>
Zur systematischen Auswertung der ausgewählten Literatur wurden die identifizierten Studien entlang klar definierter Analysekategorien untersucht. Die Analysekategorien orientieren sich unmittelbar an der Forschungsfrage und den in (@Kapitel3) dargestellten theoretischen Grundlagen. Ziel ist es, die Auswirkungen von Robotic Process Automation strukturiert und vergleichbar darzustellen.
Die erste Analysekategorie Prozessqualität umfasst alle Aussagen zu Fehlerquoten, Prozessstabilität, Servicelevel sowie zur Zuverlässigkeit automatisierter Prozessabläufe. In diese Kategorie wurden sowohl quantitative Kennzahlen als auch qualitative Bewertungen aufgenommen, die Aufschluss über Veränderungen der Prozessqualität im Zusammenhang mit dem Einsatz von RPA geben.
Die zweite Analysekategorie Effizienz bezieht sich auf zeitliche, personelle und wirtschaftliche Aspekte der Prozessleistung. Analysiert wurden insbesondere Veränderungen von Durchlauf- und Bearbeitungszeiten, der Automatisierungsgrad sowie Effekte auf den Ressourceneinsatz. Darüber hinaus wurden Aussagen zu Skalierbarkeit und langfristiger Nutzenrealisierung berücksichtigt.
Die dritte Analysekategorie Mitarbeitende fokussiert arbeitsbezogene Auswirkungen von RPA. Hierzu zählen Aspekte der Mitarbeiterzufriedenheit, Motivation, Akzeptanz sowie wahrgenommene Belastungen und Rollenveränderungen. In dieser Kategorie wurden sowohl empirische Befunde als auch theoretische Erklärungsansätze aus der Technologieakzeptanz- und Arbeitsforschung berücksichtigt.
Durch die strukturierte Zuordnung der Literatur zu diesen Analysekategorien wird eine vergleichende Betrachtung der Studien ermöglicht. Gleichzeitig bilden die Kategorien die inhaltliche Grundlage für die Analyse der Auswirkungen von RPA in (@Kapitel6) und gewährleisten eine konsistente Verbindung zwischen Theorie, Methodik und Analyse.
== Gütekriterien, Validität und Limitationen <Kapitel5.5>
Zur Sicherstellung der wissenschaftlichen Qualität der vorliegenden Arbeit wurden zentrale Gütekriterien qualitativer Forschung berücksichtigt. Ein wesentliches Kriterium ist die Transparenz des methodischen Vorgehens. Durch die systematische Beschreibung der Suchstrategie, der Auswahl- und Ausschlusskriterien sowie der Analysekategorien wird die Nachvollziehbarkeit der Literaturauswahl gewährleistet wie in (@Kapitel5.2 und @Kapitel5.4) schon angemerkt.
Die inhaltliche Validität der Arbeit ergibt sich aus der Fokussierung auf peer-reviewte IEEE-Publikationen sowie aus der theoriegeleiteten Analyse der ausgewählten Studien. Durch die Einbettung der empirischen Befunde in etablierte theoretische Konzepte aus dem Prozessmanagement, der Effizienzforschung und der Technologieakzeptanz wird eine konsistente Interpretation der Ergebnisse ermöglicht.
Gleichzeitig unterliegt die Arbeit mehreren Limitationen. Erstens basiert die Analyse ausschließlich auf vorhandener Literatur, sodass keine eigenen empirischen Daten erhoben wurde. Die Ergebnisse sind daher von der Qualität, dem Umfang und der methodischen Ausrichtung der einbezogenen Studien abhängig. Zweitens wurde die Literaturrecherche primär auf IEEE-Publikationen beschränkt, wodurch relevante Erkenntnisse aus anderen wissenschaftlichen Disziplinen oder Verlagen möglicherweise nicht berücksichtigt wurden.
Darüber hinaus weisen viele der analysierten Studien kontextspezifische Ergebnisse auf, sodass die Übertragbarkeit der Befunde auf andere Organisationen oder Prozessarten eingeschränkt sein kann. Insbesondere Unterschiede zwischen Kern- und Supportprozessen sowie zwischen verschiedenen Branchen werden in der bestehenden Literatur bislang nur teilweise systematisch untersucht.
Trotz dieser Limitationen ermöglicht das gewählte methodische Vorgehen eine strukturierte und fundierte Analyse der Auswirkungen von Robotic Process Automation. Die identifizierten Einschränkungen werden in der Diskussion (@Kapitel7) erneut aufgegriffen und kritisch reflektiert.