= 1 Einleitung
Die fortschreitende Digitalisierung fördert, dass Organisationen ihre operativen und administrativen Prozesse erhöht automatisieren, damit Effizienzpotenziale zu nutzen und Wettbewerbs- und Kostendrucke zu reagieren. Vor allem Arbeiten, die standardisiert, regelbasiert und wiederkehrend sind, bieten sich für Automatisierungstechnologien an. Robotic Process Automation (RPA) hat sich in diesem Kontext als ein gängier Ansatz zur Automatisierung digitaler Geschäftsprozesse etabliert @RPAScientificAndIndustrialMapping.
RPA steht für den Einsatz von Software-Robotern, die menschliche Interaktionen mit bestehenden IT-Systemen imitieren, indem sie strukturierte Prozessschritte über grafische Benutzeroberflächen oder definierte Schnittstellen ausführen. Die Technologie wird seit ihrer Entwicklung in den frühen 2000er-Jahren in zahlrecihe Sektoren eingestzt, einschließlich Finanzdienstleistungen, Versicherungen, Industrie und öffentlicher Verwaltung. Firmen erwarten sich von der Verwendung von RPA vor allem eine Verbesserung der Prozessqualität, Effizienzgewinne sowie eine Entlastung der Mitarbeitenden von sich wiederholenden Routinetätigkeiten @RPAScientificAndIndustrialMapping; @EffectsRPA.
Auch die arbeitswissenschaftliche Perspektive gewinnt neben den erwarteten ökonomischen Vorteilen zunehmend an Bedeutung. Nicht nur technische Abläufe werden durch RPA-Einsatz verändert: Auch Arbeitsinhalte, Rollenverteilung sowie das Verständnis von Autonomie und Kontrolle werden beeinflusst. RPA berührt zentrale Fragen der Mensch-Technik-Interaktion in digitalen Arbeitsumgebungen und ist aus betriebswirtschaftlicher sowie organisations- und arbeitswissenschaftlicher Perspektive von großer Bedeutung @Wewerka2020UserAcceptanceRPA.
== 1.1 Hintergrund und Relevanz
Die zunehmende Verbreitung von Robotic Process Automation in der Unternehmenspraxis verdeutlicht die Relevanz der Technologie als Instrument zur digitalen Prozessoptimierung. Insbesondere vor dem Hintergrund begrenzter personeller Ressourcen und steigender Anforderungen an Qualität und Geschwindigkeit von Geschäftsprozessen stellt RPA für viele organisationen einen niedrigschwelligen Einstieg in die Automatisierung dar. Da RPA bestehende IT-Systeme nutzt und keine tiefgreifenden Systemänderungen erfordert, kann die Technologie vergleichsweise schnell implementiert werden @RPAScientificAndIndustrialMapping.
Gleichzeitig gewinnt RPA auch in der wissenschaftlichen diskussion zunehmend an Bedeutung. Neben der Analyse technischer und wirtschaftlicher Effekte rücken Fragen der nachhaltigen Implementierung, der organisatorischen Einbettung sowie der Auswirkungen auf Mitarbeitende in den Fokus der Forschung. Diese Mehrdimensionalität unterstreicht die Notwendigkeit einer ganzheitlichen Betrachtung der Technologie.
== 1.2 Problemstellung
Trotz der nunehmenden praktischen Relevanz von RPA ist bislang unzureichend geklärt, wie sich der Einsatz der Technologie auf unterschiedliche Dimensionen organisationlaer Leistungen auswirkt. Währen Effizienzgewinne häufig berichtet werden, zeigen empirische Studien ein heterogenes Bild hinsichtlich der Auswirkungen auf Prozessqualität, Fehlerquoten und Prozessstabilität @EffectsRPA.
Besonders uneinheitlich ist die Befundlage im Hinblick auf die Auswirkungen von RPA auf Mitarbeitende. Einerseits wird RPA als Möglichkeit zur Reduktion monotoner Tätigkeiten und zu steigerung der Arbeitszufriedenheit beschrieben, andererseits weisen Studien auf Akzeptanzprobleme, Unsicherheiten bezüglich veränderter Rollenprofile sowie potenzielle Beslatungseffekte hin @Wewerka2020UserAcceptanceRPA. Zudem fehlen bislang integrierte Untersuchungen, die sowohl objektive Prozesskennzahlen als auch subjektive Wahrnehmungen der Mitarbeitenden berücksichtigen @RPAScientificAndIndustrialMapping.
== 1.3 Zielsetzung der Arbeit
Ziel dieser Arbeit ist es , den aktuellen wissenschaftlichen Forschungsstand zu Robotic Prozess Automation systematisch aufzuarbeiten un die Auswirkungen des RPA-Einsatzes auf drei zentrale Dimensionen digitaler Geschäftsprozesse zu analysieren: Prozessqualität, Effizienz und Mitarbeiterzufriendenheit.

Die Arbeit verfolgt einen theoriegeleiteten Ansatz und stützt sich auf etablierte Modelle der Prozessbewertung, Motivationstheorie sowie Technologieakzeptanzforschung. Durch die systematische Analayse und Synthese bestehender Studien sollen zentrale Wirkungszusammenhänge identifiziert, widersprüchliche Befunde eingeordnet und bestehende Forschungslücken aufgezeigt werden, Aufbauend darauf werden praxisorientierte Handlungsempfehlungen für eine erfolgreiche und mitarbeiterorientierte Einführung von RPA abgeleitet @Nielsen2023RPABenefits.
== 1.4 Forschungsfrage
Aus der dargestellten Problemstellung und Zielsetzung ergibt sich folgende Forschungsfrage:

Wie wirkt sich der Einsatz von Robotic Process Automation (RPA) auf die Prozessqualität, Effizienz und Mitarbeiterzufriedenheit in digitalen Geschäftsprozessen aus?
== 1.5 Aufbau der Arbeit
Die Arbeit gliedert sich wie folgt:
Kapitel 2 stellt die theoretischen Grundlagen und relevanten modelle zu Robotic Process Automation, Prozessqualität, Effizienz und Technologieakzeptanz dar.
Kapitel 3 gibt einen systematischen Überblick über den Stand der Forschung und identifiziert bestehende Forschungslücken.
Kapitel 4 beschreibt das methodische Vorgehen der systematischen Literaturrecherche.
In Kapitel 5 werden die Auswirkungen von RPA auf die untersuchten Dimensionen analysiert.
Kapitel 6 diskutiert die Ergebnisse im theoretischen Kontext.
Kapitel 7 leitet praxisorientierte Handlungsempfehlungen ab.
Kaptiel 8 schließt dann die Arbeit mit einem Fazit inkl. Ausblick ab.

= 2 Grundlagen und theoretischer Rahmen
== 2.1 Robotic Process Automation (RPA) — Definition und Funktionsweise
Robotic Process Automation bezeichnet den Einsatz von Software-Robotern zur Automatisierung strukturierter, regelbasierter Geschäftsprozesse in bestehenden IT-Systemlandschaften. Die Software-Roboter imitieren menschliche Interaktionen, indem sie Prozessschritte über grafische Benutzeroberflächen oder definierte Schnittstellen ausführen @RPAScientificAndIndustrialMapping.
Ein wesentlichen Merkmal von RPA ist die nicht-invasive Implementierung. Bestehende IT-Systeme müssen nicht verändert werden, wodurch sich RPA insbesondere für heterogene Systemlandschaften eignet. Typische Anwendungsfälle sind die Übertragung von Daten zwischen Systemen, die Verarbeitung strukturierter Dokumente sowie standardisierte Prüf- und Abgleichsprozesse @RPAScientificAndIndustrialMapping.
Die Funktionsweise von RPA basiert auf explizit modellierten Regeln und Ablaufdefinitionen, die deterministisch ausgeführt werden. Dadurch lassen sich Prozessschritte reproduzierbar und skalierbar automatisieren. Der tatsächliche Nutzen von RPA hängt jedoch maßgeblich von der Prozessreife, dem Automatisierungsgrad sowie dem Umgang mit Ausnahmen ab @EffectsRPA.
Neben technischen Aspekten beeinflusst der Einsatz von RPA auch organisatorische Strukturen. Da Software-Roboter Tätigkeiten übernehmen, die zuvor von Mitarbeitenden ausgeführt wurden, verändern sich Aufgabenverteilungen und Rollenprofile. Diese Veränderungen sind insbesondere im Hinblick auf Mitarbeiterzufriedenheit und Technologieakzeptanz von Bedeutung @Wewerka2020UserAcceptanceRPA.
== 2.2 Abgrenzung zu BPM, Workflow-Automation und KI
Zur theoretischen Einordnung von Robotic Process Automation ist eine Abgrenzung zu verwandten Automatisierungskozepten erforderlich. Business Process Management (BPM) verfolgt einen ganzheitlichen Ansatz zur Analyse, Gestaltung und kontinuierlichen Verbesserung von Geschäftsprozessen. RPA kann in diesem Kontext als operatives Werkzeug verstanden werden, das einzelne Prozessschritte automatisiert, ohne notwendigerweise eine umfassende Prozessneugestaltung vorrauszusetzen @RPAScientificAndIndustrialMapping.
Workflow-Automation basiert typischerweise auf systeminternen Prozess-Engines und erfordert eine enge Integration der beteiligten IT-Systeme. Im Vergleich dazu zeichnet sich RPA durch eine geringere technische Einstiegshürde aus, ist jedoch stärker von stabilen Benutzeroberflächen und klar definierten Regel abhängig.
KI-basierte Automatisierungslösung erweitern klassische RPA-Ansätze um adaptive Fähigkeiten wie Mustererkennung oder maschinelles Lernen. Während klassichen RPA deterministisch arbeitet, ermöglichen KI-Komponenten die Verarbeitung unstrukturierter Daten. In der Praxis stellt RPA häufig die Grundlage für weiterführende Automatisierungsinitativen dar @Nielsen2023RPABenefits.
Für die vorliegende Arbeit liegt der Fokus bewusst auf klassischer RPA, um deren Auswirkungen auf Prozessqualität, Effizienz und Mitarbeitende klar abgrenzen zu können.
== 2.3 Prozessqualität — Modelle, Kriterien und Messgrößen
Prozessqualität beschreibt den Grad, zu dem ein Geschäftsprozess definierte Anforderungen zuverlässig, fehlerarm und stabil erfüllt. In der wissenschaftlichen Literatur zu Robotic Process Automation wird Prozessqualität häufig als zentrale Zielgröße von Automatisierungsinitiativen betrachtet, insbesondere im Hinblick auf Konsistenz und Reproduzierbarkeit von Prozessabläufen @RPAScientificAndIndustrialMapping.
Zur konzeptionellen Einordnung wird Prozessqualität meist als mehrdimensionale Größe verstanden, die sowohl die Art der Prozessdurchführung als auch das erzielte Ergebnis berücksichtigt. Im Kontext digitaler Geschäftsprozesse stehen dabei insbersondere stabile Abläufe, geringe Fehleranfälligkeit sowie die Einhaltung definierter Servcielevel im Vordergrund @EffectsRPA.
Die Operationalisierung von Prozessqualität erfolgt in der Regel über quantitative Kennzahlen. Häufig verwendete Messgrößen sind unter anderem Fehlerquoten, Nachbearbeitungsraten, Prozessabbüche sowie Serviceleve-Indikatoren. Diese Kennzahlen ermöglichen eine vergleichende Bewertung von Prozessleistungen vor und nach der Einführung von Automatisierungsmaßnahmen @EffectsRPA.
Im Zusammenhang mit Robotic Process Automation wird Prozessqualität häufig mit der Annahme verknüpft, dass automatisierte Prozessschritte konsistenter ausgeführt werden als manuelle Tätigkeiten. Emperische Untersuchungen zeigen jedoch, dass Qualitätseffekte stark von der Prozessgestaltung, der Regeldefinition sowie dem Umgang mit Ausnahmen abhängen. Fehlkonfigurationen oder unzureichend modellierte Sonderfälle können neue Fehlerquellen erzeugen und die Prozessequlität negativ beeinflussen @RPAScientificAndIndustrialMapping.
Für die vorliegende Arbeit dient Prozessqualität als zentrale Analyseperspektive zur Bewertung der Auswirkungen von RPA auf digitale Geschäftsprozesse. Die dargetellten Konzepte und Messgrößen bilden die theoretische Grundlage für die spätere Analyse von Fehlerquoten, Prozessstabilität und Servicequalität in Kapitel 5.
== 2.4 Effizienz — Durchlaufzeiten, Ressourceneinsatz, Kennzahlen
Effizienz beschreibt das Verhältnis zwischen eingesetzten Ressourcen und erzielten Prozessergebnissen und stellt eine zentrale Zielgröße im Kontext der Prozessautomatisierung dar. In digitalen Geschäftsprozessen wird Effizienz insbesondere über Zeit-, Kosten- und Kapazitätsaspekte operationalisiert. Ziel ist es, Prozesse schneller, mit geringerem Ressourceneinsatz und bei gleichbleibender oder verbesserter Qualität durchzufrühren.
Zur Bewertung von Effizienz werden in der Forschung undPraxis überwiegend quantitative Kennzahlen herangezogen. Zu den wichtigsten Messgrößen zählen Durchlaufzeiten, Bearbeitungszeiten, Automatisierungsgrade sowie der personelle und technische Ressourceneinsatz. Diese Kennzahlen ermöglichen eine objektive Bewertung von Prozesseffekten und dienen als Grundlage für Vorher-Nachher-Vergleiche bei der Einführung von Automatisierungstechnologien @EffectsRPA.
Im Zusammenhang mit Robotic Process Automation wird Effizienz häufig als primärer Nutzenfaktor beschrieben. Software-Roboter können Prozessschritte kontinuierlich, mit gleichbleibender Geschwindigkeit und ohne Pause ausführen, wodurch insbesondere in transaktionsintensiven Prozessen signifikante Zeitgewinne erzielt werden können. Empirische Studien zeigen, dass sich durcch RPA sowohl Durchlaufzeiten als auch Bearbeitungszeiten deutlich reduzieren lassen, insbesondere bei hohem Standardieierungsgrad der Prozesse @EffectsRPA.
Neben zeitlichen Effekten beeinflusst RPA auch den Ressourceneinsatz. Durch die Automatisierung manueller Tätigkeiten können personelle Kapazitäten freigesetzt und auf höherwertige Aufgaben verlagert werden. Gleichzeitig entstehen neue Aufwände für Entwicklung, Betrieb und Wartung der Software-Roboter, die bei der Effizenzbewertung berücksichtigt werden müssen. Effizienzgewinne sind daher nicht ausschließlich kurzfristig zu betrachten, sondern im kontext des gesamnten Lebenszyklus von RPA-Initiativen zu bewerten @Nielsen2023RPABenefits.
Für die vorliegende Arbeit dient Effizienz als zweite zentrale Analyseperspektive zur Bewertung der Auswirkungen von RPA. Die dargestellten Kennzahlen und Konzepte bilden die theoretische Grundlage für die Analyse von Zeit-, Kosten- und Skalierungseffekten in Kapitel 5.2.
== 2.5 Mitarbeiterzufriedenheit — Motivationstheorien und Belastungsmodelle
Mitarbeiterzufriedenheit beschreibt den Grad, zu dem Mitarbeitende ihre Abreitssituation positiv bewerten und stellt eine zentrale Einflussgröße für Motivation, Leistungsbereitschaft und Akzeptanz organisationaler Veränderungen dar. Im Kontext digitaler Transformation gewinnt diese Perspektive insbesondere bei der Einführung von Automatisierungstechcnoligen an Bedeutung, da diese bestehende Arbeitsabläufe und Rollenprofile verändern.
Theoretisch lässt sich Mitarbeiterzufriendenheit unter anderem durch motavationstheoretische Ansätze erklären, die zwischen intrinsischen und extrinsischen Motivationsfaktoren unterscheiden. Tätigkeiten, die als monoton, repetitiv oder wenig sinnstiftend wahrgenommen werden, wirken sich häufig negativ auf Motvations und Zufriendheit aus. Automatisierungstechnologien wie RPA werden daher oft mit der Erwartung verbunden, Mitarbeitende von solchen Routinetätigkeiten zu entlasten und ihnen anspruchsvollere Aufgaben zu ermöglichen @Wewerka2020UserAcceptanceRPA.
Gleichzeitig weisen arbeitswissenschaftliche Modelle darauf hin, dass technologische Veränderungen auch neue Belastungen erzeugen können. Dazu zählen unter anderem Unsicherheiten hinsichtlich veränderter Rollen, erhöhte Kontrollwahrnehmung oder zusätzliche Anforderung durch Überwachung und Ausnahmebearbeitung. Ob sich RPA positiv oder negativ auf die Mitarbeiterzufriendenheit auswirkt, hängt daher stark von der konkreten Ausgesatltung der Technologieeinführung sowie von begleitenden organsatorischen Maßnahmen ab @Wewerka2020UserAcceptanceRPA.
Emperische Studien zeigen, dass die Akzeptanz von RPA eng mit der wahgenommenen Nützlichkeit, der Transparenz der Einführung sowie der Einbindung der Mitarbeitenden in dem Veränderungsprozess verknüpft ist. Werden Software-Roboter als unterstützendes Werkzeug wahrgenommen, kann dies zu einer Steigerung der Arbeitszufriendenheit führen. Fehlt hingegen eine klare Kommunikation oder Partizipation, können Wiederstände und Belastungseffekte entstehen @wewerka2020UserAcceptanceRPA.
Für die vorliegende Arbeit stellt Mitarbeiterzufriedenheit die dritte zentrale Analyseperspektive dar. Die dargestellten theoretischen Ansätze bilden die Grundlage für die spätere Analayse der Auswirkungen von RPA auf Motivation, Belastung und Akzeptanz von Mitarbeitenden in digitalen Geschäftsprozessen.
== 2.6 Technologieakzeptanz — TAM, UTAUT und Change-Management
Die Akzeptanz neuer Technologien durch Mitarbeitende stellt einen zentralen Erfolgsfaktor für Digitalisierungs- und Automatisierungsinitativen dar. Insbesondere bei der Einführung von Robotic Process Automation beeinflusst die Wahrnehmung der Technologie maßgeblich, ob die angestrebten Effizienz- und Qualitätsziele tatsächlich realisiert werden können. Technologieakzeptanz beschreibt dabei die Bereitschaft von Nutzenden, eine Technologie anzunehmen, zu verwenden und dauerhaft in Arbeitsprozesse zu integrieren.
In der Forschung zur Technologieakzeptanz haben sich verschiedene theoretische Modelle etabliert. Zentrale Annahmen dieser Modelle besagen, dass die Nutzung neuer Technologien vor allem von der wahrgenommenen Nützlichkeit sowie der wahrgenommenen Benutzerfreundlichkeit abhängt. Im Kontext von RPA bedeutet dies, dass Software-Roboter von Mitarbeitenden als unterstützend und nicht als zusätzliche Belastung wahrgenommen werden müssen, um Akzeptanz zu erzeugen @Wewerka2020UserAcceptanceRPA.
Erweiterte Akzeptanzmodelle berücksichtigen darüber hinaus soziale und organisationale Einflussfaktoren, etwa die unterstützung durch Führungskräfte, organisatorische Rahmenbedingungen oder vorhandene Kompetenzen. Studien im RPA-Kontext zeigen, dass Transparenz, Schulung und frührzeitige Einbindung der Mitarbeitenden entscheidend für4 eine positive Akzeptanzentwicklung sind @wewerka2020UserAcceptanceRPA.
Neben individuellen Akzeptanzfaktoren spielt auch das Change-Management eine zentrale Rolle bei der Einführung von RPA. Da Automatisierung häufig mit Veränderungen von Aufgaben, Verantwortlichkeiten und Abreitsabläufen einhergeht, sind begleitende Maßnahmen erforderlich, um Unsicherheiten zu reduzieren und Widerstände zu vermeiden. Ein strukturiertes Change-Management kann dazu beitragen, RPA als unterstützende Technologie zu positionieren und die langfristige Nutzung sicherzustellen @Nielsen2023RPABenefits.
Für die vorliegende Arbeit bildet die Technologieakzeptanz einen wichtigen theoretischen Bezugsrahmen, um die Auswirkungen von RPA auf Mitarbeitende zu erklären. Die dargestellten Konzepte ermöglichen es, Akzeptanz- und Widerstandeffekte systematisch zu analysieren und im späteren Verlauf der Arbeit in Beziehung zu Prozessqualität und Effizienz zu setzen.

= 3 Stand der Forschung
== 3.1 Systematische Übersicht der Literatur zu RPA
== 3.2 Befunde zur Prozessqualität
== 3.3 Befunde zur Effizienzsteigerung
== 3.4 Befunde zur Mitarbeiterzufriedenheit
== 3.5 Forschungslücken und offene Fragen
== 3.6 Zusammenfassung des Forschungsstands


= 4 Methodik

== 4.1 Forschungsdesign
== 4.2 Systematische Literaturrecherche — Vorgehen und Suchstrategie
== 4.3 Auswahl- und Ausschlusskriterien
== 4.4 Analysekategorien: Prozessqualität, Effizienz, Mitarbeitende
== 4.5 Gütekriterien, Validität und Limitationen

