= 1 Einleitung
Die fortschreitende Digitalisierung fördert, dass Organisationen ihre operativen und administrativen Prozesse erhöht automatisieren, damit Effizienzpotenziale zu nutzen und Wettbewerbs- und Kostendrucke zu reagieren. Vor allem Arbeiten, die standardisiert, regelbasiert und wiederkehrend sind, bieten sich für Automatisierungstechnologien an. Robotic Process Automation (RPA) hat sich in diesem Kontext als ein gängier Ansatz zur Automatisierung digitaler Geschäftsprozesse etabliert @RPAScientificAndIndustrialMapping.
RPA steht für den Einsatz von Software-Robotern, die menschliche Interaktionen mit bestehenden IT-Systemen imitieren, indem sie strukturierte Prozessschritte über grafische Benutzeroberflächen oder definierte Schnittstellen ausführen. Die Technologie wird seit ihrer Entwicklung in den frühen 2000er-Jahren in zahlrecihe Sektoren eingestzt, einschließlich Finanzdienstleistungen, Versicherungen, Industrie und öffentlicher Verwaltung. Firmen erwarten sich von der Verwendung von RPA vor allem eine Verbesserung der Prozessqualität, Effizienzgewinne sowie eine Entlastung der Mitarbeitenden von sich wiederholenden Routinetätigkeiten @RPAScientificAndIndustrialMapping; @EffectsRPA.
Auch die arbeitswissenschaftliche Perspektive gewinnt neben den erwarteten ökonomischen Vorteilen zunehmend an Bedeutung. Nicht nur technische Abläufe werden durch RPA-Einsatz verändert: Auch Arbeitsinhalte, Rollenverteilung sowie das Verständnis von Autonomie und Kontrolle werden beeinflusst. RPA berührt zentrale Fragen der Mensch-Technik-Interaktion in digitalen Arbeitsumgebungen und ist aus betriebswirtschaftlicher sowie organisations- und arbeitswissenschaftlicher Perspektive von großer Bedeutung @Wewerka2020UserAcceptanceRPA.
== 1.1 Hintergrund und Relevanz
Die zunehmende Verbreitung von Robotic Process Automation in der Unternehmenspraxis verdeutlicht die Relevanz der Technologie als Instrument zur digitalen Prozessoptimierung. Insbesondere vor dem Hintergrund begrenzter personeller Ressourcen und steigender Anforderungen an Qualität und Geschwindigkeit von Geschäftsprozessen stellt RPA für viele organisationen einen niedrigschwelligen Einstieg in die Automatisierung dar. Da RPA bestehende IT-Systeme nutzt und keine tiefgreifenden Systemänderungen erfordert, kann die Technologie vergleichsweise schnell implementiert werden @RPAScientificAndIndustrialMapping.
Gleichzeitig gewinnt RPA auch in der wissenschaftlichen diskussion zunehmend an Bedeutung. Neben der Analyse technischer und wirtschaftlicher Effekte rücken Fragen der nachhaltigen Implementierung, der organisatorischen Einbettung sowie der Auswirkungen auf Mitarbeitende in den Fokus der Forschung. Diese Mehrdimensionalität unterstreicht die Notwendigkeit einer ganzheitlichen Betrachtung der Technologie.
== 1.2 Problemstellung
Trotz der nunehmenden praktischen Relevanz von RPA ist bislang unzureichend geklärt, wie sich der Einsatz der Technologie auf unterschiedliche Dimensionen organisationlaer Leistungen auswirkt. Währen Effizienzgewinne häufig berichtet werden, zeigen empirische Studien ein heterogenes Bild hinsichtlich der Auswirkungen auf Prozessqualität, Fehlerquoten und Prozessstabilität @EffectsRPA.
Besonders uneinheitlich ist die Befundlage im Hinblick auf die Auswirkungen von RPA auf Mitarbeitende. Einerseits wird RPA als Möglichkeit zur Reduktion monotoner Tätigkeiten und zu steigerung der Arbeitszufriedenheit beschrieben, andererseits weisen Studien auf Akzeptanzprobleme, Unsicherheiten bezüglich veränderter Rollenprofile sowie potenzielle Beslatungseffekte hin @Wewerka2020UserAcceptanceRPA. Zudem fehlen bislang integrierte Untersuchungen, die sowohl objektive Prozesskennzahlen als auch subjektive Wahrnehmungen der Mitarbeitenden berücksichtigen @RPAScientificAndIndustrialMapping.
== 1.3 Zielsetzung der Arbeit
Ziel dieser Arbeit ist es , den aktuellen wissenschaftlichen Forschungsstand zu Robotic Prozess Automation systematisch aufzuarbeiten un die Auswirkungen des RPA-Einsatzes auf drei zentrale Dimensionen digitaler Geschäftsprozesse zu analysieren: Prozessqualität, Effizienz und Mitarbeiterzufriendenheit.

Die Arbeit verfolgt einen theoriegeleiteten Ansatz und stützt sich auf etablierte Modelle der Prozessbewertung, Motivationstheorie sowie Technologieakzeptanzforschung. Durch die systematische Analayse und Synthese bestehender Studien sollen zentrale Wirkungszusammenhänge identifiziert, widersprüchliche Befunde eingeordnet und bestehende Forschungslücken aufgezeigt werden, Aufbauend darauf werden praxisorientierte Handlungsempfehlungen für eine erfolgreiche und mitarbeiterorientierte Einführung von RPA abgeleitet @Nielsen2023RPABenefits.
== 1.4 Forschungsfrage
Aus der dargestellten Problemstellung und Zielsetzung ergibt sich folgende Forschungsfrage:

Wie wirkt sich der Einsatz von Robotic Process Automation (RPA) auf die Prozessqualität, Effizienz und Mitarbeiterzufriedenheit in digitalen Geschäftsprozessen aus?
== 1.5 Aufbau der Arbeit
Die Arbeit gliedert sich wie folgt:
Kapitel 2 stellt die theoretischen Grundlagen und relevanten modelle zu Robotic Process Automation, Prozessqualität, Effizienz und Technologieakzeptanz dar.
Kapitel 3 gibt einen systematischen Überblick über den Stand der Forschung und identifiziert bestehende Forschungslücken.
Kapitel 4 beschreibt das methodische Vorgehen der systematischen Literaturrecherche.
In Kapitel 5 werden die Auswirkungen von RPA auf die untersuchten Dimensionen analysiert.
Kapitel 6 diskutiert die Ergebnisse im theoretischen Kontext.
Kapitel 7 leitet praxisorientierte Handlungsempfehlungen ab.
Kaptiel 8 schließt dann die Arbeit mit einem Fazit inkl. Ausblick ab.

= 2 Grundlagen und theoretischer Rahmen
== 2.1 Robotic Process Automation (RPA) — Definition und Funktionsweise
Robotic Process Automation bezeichnet den Einsatz von Software-Robotern zur Automatisierung strukturierter, regelbasierter Geschäftsprozesse in bestehenden IT-Systemlandschaften. Die Software-Roboter imitieren menschliche Interaktionen, indem sie Prozessschritte über grafische Benutzeroberflächen oder definierte Schnittstellen ausführen @RPAScientificAndIndustrialMapping.
Ein wesentlichen Merkmal von RPA ist die nicht-invasive Implementierung. Bestehende IT-Systeme müssen nicht verändert werden, wodurch sich RPA insbesondere für heterogene Systemlandschaften eignet. Typische Anwendungsfälle sind die Übertragung von Daten zwischen Systemen, die Verarbeitung strukturierter Dokumente sowie standardisierte Prüf- und Abgleichsprozesse @RPAScientificAndIndustrialMapping.
Die Funktionsweise von RPA basiert auf explizit modellierten Regeln und Ablaufdefinitionen, die deterministisch ausgeführt werden. Dadurch lassen sich Prozessschritte reproduzierbar und skalierbar automatisieren. Der tatsächliche Nutzen von RPA hängt jedoch maßgeblich von der Prozessreife, dem Automatisierungsgrad sowie dem Umgang mit Ausnahmen ab @EffectsRPA.
Neben technischen Aspekten beeinflusst der Einsatz von RPA auch organisatorische Strukturen. Da Software-Roboter Tätigkeiten übernehmen, die zuvor von Mitarbeitenden ausgeführt wurden, verändern sich Aufgabenverteilungen und Rollenprofile. Diese Veränderungen sind insbesondere im Hinblick auf Mitarbeiterzufriedenheit und Technologieakzeptanz von Bedeutung @Wewerka2020UserAcceptanceRPA.
== 2.2 Abgrenzung zu BPM, Workflow-Automation und KI
Zur theoretischen Einordnung von Robotic Process Automation ist eine Abgrenzung zu verwandten Automatisierungskozepten erforderlich. Business Process Management (BPM) verfolgt einen ganzheitlichen Ansatz zur Analyse, Gestaltung und kontinuierlichen Verbesserung von Geschäftsprozessen. RPA kann in diesem Kontext als operatives Werkzeug verstanden werden, das einzelne Prozessschritte automatisiert, ohne notwendigerweise eine umfassende Prozessneugestaltung vorrauszusetzen @RPAScientificAndIndustrialMapping.
Workflow-Automation basiert typischerweise auf systeminternen Prozess-Engines und erfordert eine enge Integration der beteiligten IT-Systeme. Im Vergleich dazu zeichnet sich RPA durch eine geringere technische Einstiegshürde aus, ist jedoch stärker von stabilen Benutzeroberflächen und klar definierten Regel abhängig.
KI-basierte Automatisierungslösung erweitern klassische RPA-Ansätze um adaptive Fähigkeiten wie Mustererkennung oder maschinelles Lernen. Während klassichen RPA deterministisch arbeitet, ermöglichen KI-Komponenten die Verarbeitung unstrukturierter Daten. In der Praxis stellt RPA häufig die Grundlage für weiterführende Automatisierungsinitativen dar @Nielsen2023RPABenefits.
Für die vorliegende Arbeit liegt der Fokus bewusst auf klassischer RPA, um deren Auswirkungen auf Prozessqualität, Effizienz und Mitarbeitende klar abgrenzen zu können.
== 2.3 Prozessqualität — Modelle, Kriterien und Messgrößen
Prozessqualität beschreibt den Grad, zu dem ein Geschäftsprozess definierte Anforderungen zuverlässig, fehlerarm und stabil erfüllt. In der wissenschaftlichen Literatur zu Robotic Process Automation wird Prozessqualität häufig als zentrale Zielgröße von Automatisierungsinitiativen betrachtet, insbesondere im Hinblick auf Konsistenz und Reproduzierbarkeit von Prozessabläufen @RPAScientificAndIndustrialMapping.
Zur konzeptionellen Einordnung wird Prozessqualität meist als mehrdimensionale Größe verstanden, die sowohl die Art der Prozessdurchführung als auch das erzielte Ergebnis berücksichtigt. Im Kontext digitaler Geschäftsprozesse stehen dabei insbersondere stabile Abläufe, geringe Fehleranfälligkeit sowie die Einhaltung definierter Servcielevel im Vordergrund @EffectsRPA.
Die Operationalisierung von Prozessqualität erfolgt in der Regel über quantitative Kennzahlen. Häufig verwendete Messgrößen sind unter anderem Fehlerquoten, Nachbearbeitungsraten, Prozessabbüche sowie Serviceleve-Indikatoren. Diese Kennzahlen ermöglichen eine vergleichende Bewertung von Prozessleistungen vor und nach der Einführung von Automatisierungsmaßnahmen @EffectsRPA.
Im Zusammenhang mit Robotic Process Automation wird Prozessqualität häufig mit der Annahme verknüpft, dass automatisierte Prozessschritte konsistenter ausgeführt werden als manuelle Tätigkeiten. Emperische Untersuchungen zeigen jedoch, dass Qualitätseffekte stark von der Prozessgestaltung, der Regeldefinition sowie dem Umgang mit Ausnahmen abhängen. Fehlkonfigurationen oder unzureichend modellierte Sonderfälle können neue Fehlerquellen erzeugen und die Prozessequlität negativ beeinflussen @RPAScientificAndIndustrialMapping.
Für die vorliegende Arbeit dient Prozessqualität als zentrale Analyseperspektive zur Bewertung der Auswirkungen von RPA auf digitale Geschäftsprozesse. Die dargetellten Konzepte und Messgrößen bilden die theoretische Grundlage für die spätere Analyse von Fehlerquoten, Prozessstabilität und Servicequalität in Kapitel 5.
== 2.4 Effizienz — Durchlaufzeiten, Ressourceneinsatz, Kennzahlen
Effizienz beschreibt das Verhältnis zwischen eingesetzten Ressourcen und erzielten Prozessergebnissen und stellt eine zentrale Zielgröße im Kontext der Prozessautomatisierung dar. In digitalen Geschäftsprozessen wird Effizienz insbesondere über Zeit-, Kosten- und Kapazitätsaspekte operationalisiert. Ziel ist es, Prozesse schneller, mit geringerem Ressourceneinsatz und bei gleichbleibender oder verbesserter Qualität durchzufrühren.
Zur Bewertung von Effizienz werden in der Forschung undPraxis überwiegend quantitative Kennzahlen herangezogen. Zu den wichtigsten Messgrößen zählen Durchlaufzeiten, Bearbeitungszeiten, Automatisierungsgrade sowie der personelle und technische Ressourceneinsatz. Diese Kennzahlen ermöglichen eine objektive Bewertung von Prozesseffekten und dienen als Grundlage für Vorher-Nachher-Vergleiche bei der Einführung von Automatisierungstechnologien @EffectsRPA.
Im Zusammenhang mit Robotic Process Automation wird Effizienz häufig als primärer Nutzenfaktor beschrieben. Software-Roboter können Prozessschritte kontinuierlich, mit gleichbleibender Geschwindigkeit und ohne Pause ausführen, wodurch insbesondere in transaktionsintensiven Prozessen signifikante Zeitgewinne erzielt werden können. Empirische Studien zeigen, dass sich durcch RPA sowohl Durchlaufzeiten als auch Bearbeitungszeiten deutlich reduzieren lassen, insbesondere bei hohem Standardieierungsgrad der Prozesse @EffectsRPA.
Neben zeitlichen Effekten beeinflusst RPA auch den Ressourceneinsatz. Durch die Automatisierung manueller Tätigkeiten können personelle Kapazitäten freigesetzt und auf höherwertige Aufgaben verlagert werden. Gleichzeitig entstehen neue Aufwände für Entwicklung, Betrieb und Wartung der Software-Roboter, die bei der Effizenzbewertung berücksichtigt werden müssen. Effizienzgewinne sind daher nicht ausschließlich kurzfristig zu betrachten, sondern im kontext des gesamnten Lebenszyklus von RPA-Initiativen zu bewerten @Nielsen2023RPABenefits.
Für die vorliegende Arbeit dient Effizienz als zweite zentrale Analyseperspektive zur Bewertung der Auswirkungen von RPA. Die dargestellten Kennzahlen und Konzepte bilden die theoretische Grundlage für die Analyse von Zeit-, Kosten- und Skalierungseffekten in Kapitel 5.2.
== 2.5 Mitarbeiterzufriedenheit — Motivationstheorien und Belastungsmodelle
Mitarbeiterzufriedenheit beschreibt den Grad, zu dem Mitarbeitende ihre Abreitssituation positiv bewerten und stellt eine zentrale Einflussgröße für Motivation, Leistungsbereitschaft und Akzeptanz organisationaler Veränderungen dar. Im Kontext digitaler Transformation gewinnt diese Perspektive insbesondere bei der Einführung von Automatisierungstechcnoligen an Bedeutung, da diese bestehende Arbeitsabläufe und Rollenprofile verändern.
Theoretisch lässt sich Mitarbeiterzufriendenheit unter anderem durch motavationstheoretische Ansätze erklären, die zwischen intrinsischen und extrinsischen Motivationsfaktoren unterscheiden. Tätigkeiten, die als monoton, repetitiv oder wenig sinnstiftend wahrgenommen werden, wirken sich häufig negativ auf Motvations und Zufriendheit aus. Automatisierungstechnologien wie RPA werden daher oft mit der Erwartung verbunden, Mitarbeitende von solchen Routinetätigkeiten zu entlasten und ihnen anspruchsvollere Aufgaben zu ermöglichen @Wewerka2020UserAcceptanceRPA.
Gleichzeitig weisen arbeitswissenschaftliche Modelle darauf hin, dass technologische Veränderungen auch neue Belastungen erzeugen können. Dazu zählen unter anderem Unsicherheiten hinsichtlich veränderter Rollen, erhöhte Kontrollwahrnehmung oder zusätzliche Anforderung durch Überwachung und Ausnahmebearbeitung. Ob sich RPA positiv oder negativ auf die Mitarbeiterzufriendenheit auswirkt, hängt daher stark von der konkreten Ausgesatltung der Technologieeinführung sowie von begleitenden organsatorischen Maßnahmen ab @Wewerka2020UserAcceptanceRPA.
Emperische Studien zeigen, dass die Akzeptanz von RPA eng mit der wahgenommenen Nützlichkeit, der Transparenz der Einführung sowie der Einbindung der Mitarbeitenden in dem Veränderungsprozess verknüpft ist. Werden Software-Roboter als unterstützendes Werkzeug wahrgenommen, kann dies zu einer Steigerung der Arbeitszufriendenheit führen. Fehlt hingegen eine klare Kommunikation oder Partizipation, können Wiederstände und Belastungseffekte entstehen @wewerka2020UserAcceptanceRPA.
Für die vorliegende Arbeit stellt Mitarbeiterzufriedenheit die dritte zentrale Analyseperspektive dar. Die dargestellten theoretischen Ansätze bilden die Grundlage für die spätere Analayse der Auswirkungen von RPA auf Motivation, Belastung und Akzeptanz von Mitarbeitenden in digitalen Geschäftsprozessen.
== 2.6 Technologieakzeptanz — TAM, UTAUT und Change-Management
Die Akzeptanz neuer Technologien durch Mitarbeitende stellt einen zentralen Erfolgsfaktor für Digitalisierungs- und Automatisierungsinitativen dar. Insbesondere bei der Einführung von Robotic Process Automation beeinflusst die Wahrnehmung der Technologie maßgeblich, ob die angestrebten Effizienz- und Qualitätsziele tatsächlich realisiert werden können. Technologieakzeptanz beschreibt dabei die Bereitschaft von Nutzenden, eine Technologie anzunehmen, zu verwenden und dauerhaft in Arbeitsprozesse zu integrieren.
In der Forschung zur Technologieakzeptanz haben sich verschiedene theoretische Modelle etabliert. Zentrale Annahmen dieser Modelle besagen, dass die Nutzung neuer Technologien vor allem von der wahrgenommenen Nützlichkeit sowie der wahrgenommenen Benutzerfreundlichkeit abhängt. Im Kontext von RPA bedeutet dies, dass Software-Roboter von Mitarbeitenden als unterstützend und nicht als zusätzliche Belastung wahrgenommen werden müssen, um Akzeptanz zu erzeugen @Wewerka2020UserAcceptanceRPA.
Erweiterte Akzeptanzmodelle berücksichtigen darüber hinaus soziale und organisationale Einflussfaktoren, etwa die unterstützung durch Führungskräfte, organisatorische Rahmenbedingungen oder vorhandene Kompetenzen. Studien im RPA-Kontext zeigen, dass Transparenz, Schulung und frührzeitige Einbindung der Mitarbeitenden entscheidend für4 eine positive Akzeptanzentwicklung sind @wewerka2020UserAcceptanceRPA.
Neben individuellen Akzeptanzfaktoren spielt auch das Change-Management eine zentrale Rolle bei der Einführung von RPA. Da Automatisierung häufig mit Veränderungen von Aufgaben, Verantwortlichkeiten und Abreitsabläufen einhergeht, sind begleitende Maßnahmen erforderlich, um Unsicherheiten zu reduzieren und Widerstände zu vermeiden. Ein strukturiertes Change-Management kann dazu beitragen, RPA als unterstützende Technologie zu positionieren und die langfristige Nutzung sicherzustellen @Nielsen2023RPABenefits.
Für die vorliegende Arbeit bildet die Technologieakzeptanz einen wichtigen theoretischen Bezugsrahmen, um die Auswirkungen von RPA auf Mitarbeitende zu erklären. Die dargestellten Konzepte ermöglichen es, Akzeptanz- und Widerstandeffekte systematisch zu analysieren und im späteren Verlauf der Arbeit in Beziehung zu Prozessqualität und Effizienz zu setzen.

= 3 Stand der Forschung
== 3.1 Systematische Übersicht der Literatur zu RPA
Die wissenschaftliche Auseinandersetzung mit Robotic Process Automation hat in den vergangen Jahren deutlich zugenommen, parallel zur wachsenden praktischen Verbreitung der Technologie. Ein Großteil der bestehenden Forschung beschäftigt sich mit der konzeptionellen Einordnung von RPA, der Beschreibung von Einsatzszenarien sowie der Analyse potenziellen Nutzen- und Risikoaspekte. Systematische Übersichtsarbeiten zeigen, dass RPA insbesondere in stark standardisierten, transaktionsorientierten Geschäftsprozesen eingesetzt wird @RPAScientificAndIndustrialMapping.
Die Literatur zu RPA lässt sich grob in drei thematische Schwerpunkte unterteilen: Erstens fokussieren zahlreiche Studien auf technologische und prozessuale Aspekte, etwa die Funktionsweise von RPA, typische Einsatzbereiche sowie Implementierungsansätze. Zweitesns befassen sich empirische Arbeiten mit den Auswirkungen von RPA auf Effizienz und Prozessleistung, wobei  insbersondere Zeitersparnisse, Kosteneffekte und Automatisierungsgrade analysisert werden @EffectsRPA. Drittens rückt zunehmend die Mitarbeitendenperspektive in den Fokus, insbeondere im Hinblick auf Akzeptanz, Rollenveränderungen und arbeitsbezogene Auswirkungen @Wewerka2020UserAcceptanceRPA.
Methodisch dominieren in der RPA-Forschung qualitative Fallstudien, konzeptionelle Arbeiten sowie vereinzelt quanitative Analysen. Während Fallstudien detaillierte Einblicke in konkrete Anwendungskontexte liefern, sind vergleichende quantitative Untersuchungen bislang seltener. Insbesondere Studien, die objektive Prozesskennzahlen mit subjektiven Wahrnehmungen von Mitarbeitenden kombinieren, sind bislang unterrepräsentiert @RPAScientificAndIndustrialMapping.
Darüber hinaus zeigt die Literatur, dass Effekte von RPA stark vom jeweiligen Anwendungskontext abhängen. Faktoren wie Prozessreife, Standardisierungsgrad, organisatorische Einbettung und begleitende Change-Management-Maßnahmen beeinflussen maßgeblich, ob RPA positive Auswirkungen auf Effizienz und Qualität entfalten kann @Nielsen2023RPABenefits. Eine isolierte Betrachtung der Technologie ohne Berücksichtigung dieser Kontextfaktoren greift daher häufig zu kurz.
Zusammenfassend lässt sich festhalten, dass die bestehende Forschung wertvolle Erkenntnisse zu Einsatzmöglichkeiten und Potenzialen von RPA liefert, jedoch bislang kein einheitliches Bild hinsichtlich der Wirkung auf Prozessqualität, Effizienz und Mitarbeiterzufriendenheit zeichnet. Diese Heterogenität der Befunde bildet die Grundlage für die nachfolgenden Kapitel, in denen die empirischen Ergebnisse entlang der drei Untersuchtungsdimensionen systematisch aufgearbeitet werden.
== 3.2 Befunde zur Prozessqualität
Die Auswirkungen von Robotic Process Automation auf die Prozessqualität werden in der bestehenden Literatur überwigend positiv bewertet, jedoch zeigen empirische Studien ein differenziertes und teilweise widersprüchliches Bild. Prozessqualität wird dabei vor allem anhand von Kriterien wie Fehlerquoten, Prozesstabilität und Servicelevel analysiert. RPA wird häufig mit der Erwartung verbunden, dass automatisierte Prozessschritte konsistenter und weniger fehleranfällig ausgeführt werden als manuelle Tätigkeiten @RPAScientificAndIndustrialMapping.
Empirische Untersuchungen berichten, insbesondere von einer Reduktion manueller Eingabefehler sowie einer erhöhten Reproduzierbarkeit von Prozessabläufen. Da Software-Roboter deterministisch arbeiten und definierte Regeln strikt einhalten, lassen sich Abweichungen durch menschliche Ermüdung oder Unaufmerksamkeit vermeiden. Diese Effekte treten vor allem in stark standardisierten und strukturierten Prozessen auf @EffectsRPA.
Gleichzeitig weisen Studien darauf hin, dass der Einsatz von RPA neue Risiken für die Prozessqualität mit sich bringen kann. Fehlerhafte Regeldefinitionen, unzureichend modellierte Ausnahemfälle oder Änderung an Benutzeroberflächen können dazu führen, dass automatisierte Prozesse fehlerhaft oder instabil ausgeführt werden. In solchen Fällen kann sich die Prozessqualität trotz Automatisierung sogar verschlechtern @RPAScientificAndIndustrialMapping.
Darüber hinaus zeigen empirische Befunde, dass Qualtiätseffekte von RPA stark vom organisatiorischen Kontext abhängen. Prozesse mit hoher Variabilität oder einem hohen Anteil unstrukturierter Daten profitieren deutlich weniger von RPA als klar definierte Routinetätigkeiten. Auch fehlende Governance-Strukturen und unzureichendes Monitoring können dazu beitragen, dass potenzielle Qualitätsgewinne nicht realisiert werden @Nielsen2023RPABenefits.
Zusammenfassend lässt sich festhalten, dass RPA das Potenzial hat, die Prozessqualität in digitalen Geschäftsprozessen zu verbessern, diese Effekte jedoch nicht automatisch eintreten. Vielmehr sind sie an Voraussetzungen wie geeignete Prozessauswahl, sorgfältige Modellierung und kontinuierliche Überwachung geknüpft. Diese Erkenntnisse unterstreichen die Notwendigkeit einer differenzierten Bewertung der Technologie, die in den nachfolgenden Kapiteln weiter vertieft wird.
== 3.3 Befunde zur Effizienzsteigerung
Die Effizenzsteigerung zählt zu den am häufigsten genannten Zielsetzungen beim Einsatz von Robotic Process Automation und stellt einen zentralen Fokus der empirischen RPA-Forschung dar. Effizienz wird dabei überwigend anhand von Kennzahlen wie Durchlaufzeiten, bearbeitungszeiten, Automatisierungsgrad sowie Kosten- und Ressourceneffekten bewertet @EffectsRPA.
Empirische Studien zeigen, dass der Einsatz von RPA insbesondere in stark standardisierten und transaktionsintensiven Prozessen zu signifikanten Zeitersparnissen führen kann. Software-Roboter arbeiten kontinuierlich, mit gleichbleibender Geschwindigkeit und ohne Pausen, wodruch sich Durchlauf- und Bearbeitungszeiten deutlich reduzieren lassen. Diese Effekte sind vor allem in Supoortprozessen wie Rechnungsverarbeitung, Stammdatenpflege oder Reporting zu beobachten @EffectsRPA.
Neben zeitlichen Effekten berichten Studien auch von positiven Auswirkungen auf den Ressourceneinsatz. Durch die Automatisierung manueller Routinetätigkeiten können personelle Kapazitäten freigesetzt und für komplexere oder wertschöpfendere Aufgaben eingesetzt werden. Gleichzeitig zeigen untersuchungen, dass Effizienzgewinne nicht ausschließlich durch Personaleinsparungen entstehen, sondern auch durch verbesserte Skalierbarkeit und höhere Prozessstabilität @Nielsen2023RPABenefits.
Allerdings weisen empirische Befunde drauf hin, dass Effizienzgewinne durch RPA stark kontextabhängig sind. Prozesse mit hoher Veriabilität, häufig Ausnahmen oder unzureichender Standardisierung profitieren deutlich weniger von RPA. Zudem entstehen zusätzliche Aufwände für Entwicklung, Betrieb und Wartung der Software-Roboter, die insbesondere bei langfristiger Betrachtung berücksichtigt werden müssen @RPAScientificAndIndustrialMapping.
Zusammenfassend lässt sich festhalten, dass RPA ein hohes Potenzial zur Effizienzsteigerung bietet, diese Effekte jedoch nicht autoamtisch eintreten. Vielmehr hängen sie von der geeigneten Prozessauswahl, dem Automatisierungsgrad sowie der organisatorischen Einbettung der Technologie ab. Diese differenzierte Befundlage bildet die Grunddlage für die weitere Analyse der Effizenzdimension in Kapitel 5.2.
== 3.4 Befunde zur Mitarbeiterzufriedenheit
Die Auswirkungen von Robotic Process Automation auf die Mitarbeiterzufriedenheit werden in der bestehenden Forschung deutlich ambivalenter bewertet als Effekte auf Prozessqualität oder Effizienz. Während RPA häufig mit der Erwartung verbunden ist, Mitarbeitende von monotonen oder repetitiven Tätigkeiten zu entlasten, zeigen empirische Studien ein differenziertes Bild hinsichtlich Motivation, Belastung und Akzeptanz @Wewerka2020UserAcceptanceRPA.
Ein Teil der Literatur berichtet von positiven Effekten auf die Arbeitszufriedenheit, insbesondere wenn RPA dazu beiträgt, routinemäßige Tätigkeiten zu reduzieren und Mitarbeitende mehr Zeit für anspruchsvollere Aufgaben zu verschaffen. In solchen Fällen wird RPA als unterstützende Technolige wahrgenommen, die Autonomie und wahrgenommene Nützlichkeit der Arbeit erhöhen kann @Wewerka2020UserAcceptanceRPA.
Demgegeüber weisen andere Studien auf potenzielle negative Effekte hin. Dazu zählen Unsicherheiten im Hinblick auf veränderte Rollenprofile, Befürchtungen hinsichtlich Arbeitsplatzsicherheit sowie eine erhöhte Belastung durch Überwachung oder die Bearbeitung von Ausnahmefällen, die nicht automatisiert werden können. Insbesondere bei fehlender Transparenz und unzureichender Kommunikation im Einführungsprozess kann RPA als Bedrohung wahrgenommen werden @Wewerka2020UserAcceptanceRPA.
Erpirische Befunde zeigen zudem, dass die Akzeptanz von RPA stark von organisationalen Rahmenbedingungen abhängt. Eine frühzeitige Einbindung der Mitarbeitenden, klare Kommunikation der Ziele sowie Schulungs- und Qualifizierungsmaßnahmen wirken sich positiv auf die Wahrnehmung und Nutzung der Technologie aus. Fehlen diese begleitenden Maßnahmen, steigt die Wahrscheinlichkeit von Widerständen und Akzeptanzproblemen @RPAScientificAndIndustrialMapping.
Zusammenfassend lässt sich festhalten, dass RPA weder per se zu einer Steigerung noch zu einer Reduktion der Mitarbeiterzufriedenheit führt. Vielmehr hängen die arbeitsbezogenen Effekte maßgeblich von der konkreten Gestaltung der RPA-Einführung, dem organisationalen Kontext sowie der Rolle der Mitarbeitenden im automatisierten Prozess ab. Diese Befunde unterstreichen die Bedeutung einer mitarbeiterorientierten Implementationsstrategie, die in den folgenden Kapiteln weiter aufgegriffen wird.
== 3.5 Forschungslücken und offene Fragen
Die Analyse des bisherigen Forschungsstands zeigt, dass Robotic Process Automation in der Literatur bereits umfassend beschrieben wird, jedoch weiterhin wesentliche Forschungslücken bestehen. Insbesondere mangelt es an einer integrierten Betrachtung der Auswirkungen von RPA auf Prozessqualität, Effizienz und Mitarbeiterzufriendenheit. Viele Studien fokussieren sich isoliert auf einzelne Dimensionen, wordurch ein ganzheitliches Verständnis der Wirkungszusammenhänge erschwert wird @RPAScientificAndIndustrialMapping.
Eine Zentrale Forschungslücke besteht in der begrenzten Anzahl an empirischer Studien, die objektive Prozesskennzahlen mit subjektiven Wahrnehmungen der Mitarbeitenden kombinieren. Während Effizienzgewinne häufig anhand quantitativer Metriken untersucht werden, bleiben arbeitesbezogene Effekte wie Motivation, Akezeptanz oder wahrgenommene Belastung oft unterbelichtet oder werden lediglich qualitativ erfasst @EffectsRPA; @Wewerka2020UserAcceptanceRPA.
Darüber hinaus weisen bestehende Untersuchungen eine starke Kontextabhängigkeit auf. Effekte von RPA variieren erheblich in Abhängigkeit von Prozessart, Automatisierungsgrad und organisationalen Rahmenbedingungen. Insbesondere Unterschiede zwischen operativen Kernprozessen und unterstützenden Supportprozessen werden bislang nur unzureichend systematisch analysiert @Nielsen2023RPABenefits.
Ein weiteres Defizit liegt in der begrenzten theoretischen Fundierung vieler empirischer Arbeiten. Obwohl Konzepte wie Technologieakzeptanz und Motivation vereinzelt herangezogen werden, fehlt häufig eine konsistente theoretische Integration, um die beobachteten Effekte von RPA auf Mitarbeitende und Prozesse zu erklären @Wewerka2020UserAcceptanceRPA. Dies erschwert sowohl die Vergleichbarkeit bestehnder Studien als auch die Ableitung generalisierbarer Handlungsempfehlungen.
Zusmamenfassend besteht ein Bedarf an theoriegeleiteten Untersuchungen, die die Auswirkungen von RPA multidimensional erfasen und sowohl technische als auch menschliche Aspekte berücksichtigen. An dieser Stelle setzt die vorliegende Arbeit an, indem sie bestehende empirische Befunde systematisch synthetisiert und entlang der Dimensionen Prozessqualität, Effizienz und Mitarbeiterzufriedenheit analysiert.
== 3.6 Zusammenfassung des Forschungsstands
Der Überblick über den bisherigen Forschungsstand zeigt, dass Robotic Process Automation ein intesiv untersuchtes und zugleich dynamisches Forschungsfeld darstellt. Die vorhandene Literatur liefert wertvolle Erkenntnisse zu Einsatzmöglichkeiten, Potenzialen und Herausforderungen der Tecchnologiem, insbesondere im Hinblick auf Effizienzsteigerungen und die Automatisierung standardisierter Geschäftsprozesse @RPAScientificAndIndustrialMapping; @EffectsRPA.
Gleichzeitig verdeutlichen die empirischen Befunde, dass die Auswirkungen von RPA auf Prozessqualität, Effizienz und Mitarbeiterzufriedenheit nciht eindeutig und teilweise widersprüchlich sind. Während Effizienzgewinne in vielen Studien nachgewisen werden, hängen Effekte auf Prozessqualität und arbeitsbezogene Faktoren stark vom jeweiligen Anwendungskontext, der Prozessgestaltung sowie der organisationalen Einbettung ab @EffectsRPA; @Wewerka2020UserAcceptanceRPA.
Insbesondere zeigt sich, dass Mitarbeiterzufriedenheit und Technologieakzeptanz eine zentrale Rolle für den Erfolg von RPA-Initativen spiele. Ohne geeignete begleitende Maßnahmen wie transparente Kommunikation, Schulung und Einbindung der Mitarbeitenden können potenzielle Effizienz- und Qualitätsgewinne nicht vollständig realisiert werden @Wewerka2020UserAcceptanceRPA.
Zusammenfassend lässt sich festhalten, dass trotz wachsender Literatur weiterhin ein Bedarf an integrierten, theoriegeleiteten Analysen besteht, die technische Prozesskennzahlen und menschliche Faktoren gemeinsam betrachten. Diese Erkenntnis bildet die Grundlage für das methodische Vorgehen der vorliegenden Arbeit, das im folgenden Kapitel beschrieben wird.

= 4 Methodik

== 4.1 Forschungsdesign
== 4.2 Systematische Literaturrecherche — Vorgehen und Suchstrategie
== 4.3 Auswahl- und Ausschlusskriterien
== 4.4 Analysekategorien: Prozessqualität, Effizienz, Mitarbeitende
== 4.5 Gütekriterien, Validität und Limitationen

