= 5 Analyse: Auswirkungen von RPA auf digitale Geschäftsprozesse
In diesem Kapitel werden die im Rahmen der systematischen Literaturrecherche identifizierten Studien hinsichtlich der Auswirkungen von Robotic Process Automation (RPA) auf Prozessqualität, Effizienz und Mitarbeiter ausgewertet. Die Analyse folgt den in Kapitel 4 beschriebenen Analysekategorien und zielt darauf ab, wiederkehrende Muster sowie zentrale Einflussfaktoren zu identifizieren.

== 5.1 Auswirkungen auf Prozessqualität

=== 5.1.1 Fehlerquote und Prozessstabilität
Ein Großteil der analysierten Studien zeigt, dass der Einsatz von RPA zu einer Reduktion manueller Fehler beitragen kann @EffectsRPA;@RPAScientificAndIndustrialMapping;@Nielsen2023RPABenefits. Die deterministische Abarbeitung regelbasierter Prozessschritte verhindert typische menschliche Fehler, die durch Routine, Zeitdruck oder Ermüdung entstehen. Dadurch erhöht sich insbesondere in stark standardisierten Prozessen die Prozessstabilität @Willcocks2017RPA;@RPAScientificAndIndustrialMapping. Allerdings wird in mehreren Arbeiten deutlich, dass RPA gleichzeitig neue Abhängigkeiten schafft. Fehler in der Regelkonfiguration, unerwartete Ausnahmen oder Änderungen an Benutzeroberflächen können systematisch zu Fehlausführungen führen. Während menschlich verursachte Fehler häufig situativ korrigiert werden können, wirken Fehlkonfigurationen in Bots mitunter potenzierend. Prozessstabilität entsteht daher nur dann, wenn Prozesse ausreichend strukturiert sind und Anpassungsmechanismen existieren @Syed2020IPA;@vanderAalst2018PM.
=== 5.1.2 Servicequalität und Servicelevel
Die Literatur macht deutlich, dass Unternehmen durch RPA in der Lage sind, Servicelevel-Vorgaben zuverlässiger einzuhalten @EffectsRPA;@RPAScientificAndIndustrialMapping. Da Software-Bots unabhängig von Arbeitszeiten oder Ressourcenverfügbarkeit arbeiten, lassen sich Bearbeitungs- und Reaktionszeiten systematisch verkürzen. In der Folge berichten viele Organisationen von einer gleichmäßigeren und verlässlicheren Leistungserbringung @Willcocks2017RPA. Gleichzeitig weisen einzelne Studien darauf hin, dass durch die zunehmende Standardisierung die individuelle Fallbearbeitung eingeschränkt sein kann @Siderska2020RPA;@Lacity2021RPA. Besonders in komplexen oder kundenorientierten Prozessen bleibt menschliche Intervention daher weiterhin erforderlich.
=== 5.1.3 Kundenerwartungen und Prozessrobustheit
Die Robustheit digitaler Geschäftsprozesse steigt insbesondere in Bereichen, in denen zuvor personengebundene Arbeitsschritte dominierten. Kunden profitieren in solchen Prozessen von konsistenten Ergebnissen und einer verlässlichen Bearbeitung. Gleichzeitig verstärkt RPA die Abhängigkeit von Systemverfügbarkeit sowie Datenqualität. In Organisationen, die über kein strukturiertes Monitoring verfügen, können Störungen länger unentdeckt bleiben. Insgesamt lässt sich festhalten, dass RPA einen positiven Einfluss auf die Prozessqualität haben kann, dieser jedoch stark vom Prozessreifegrad und der technischen sowie organisatorischen Einbettung abhängt.
== 5.2 Auswirkungen auf Effizienz
=== 5.2.1 Durchlauf- und Bearbeitungszeiten
Nahezu alle untersuchten Studien bestätigen, dass RPA einen deutlichen Einfluss auf die Verringerung von Durchlauf- und Bearbeitungszeiten hat. Da Software-Roboter Prozessschritte ohne Unterbrechung und mit konstanter Geschwindigkeit ausführen, werden Routineaufgaben effizienter abgewickelt. Besonders stark fallen diese Effekte in daten- und transaktionsintensiven Prozessen aus. Die erzielten Zeitgewinne hängen allerdings vom Automatisierungsgrad und der Notwendigkeit manueller Nachbearbeitung ab @EffectsRPA;@RPAScientificAndIndustrialMapping;@Nielsen2023RPABenefits.
=== 5.2.2 Automatisierungsgrad und Ressourceneinsatz
RPA führt selten zu einem vollständigen Ersatz menschlicher Arbeit. Häufig verändern sich vielmehr die Aufgabenschwerpunkte. Manuelle Dateneingabe tritt in den Hintergrund, während Überwachung, Fehlerbearbeitung und Prozesskoordination an Bedeutung gewinnen. Dadurch verschieben sich Kompetenzanforderungen in Richtung analytischer und technischer Fähigkeiten. Personelle Entlastung findet vor allem in monotonen Tätigkeitsbereichen statt, während qualifizierte Tätigkeiten an Bedeutung gewinnen.
=== 5.2.3 Skalierungseffekte und Kosten
Die wirtschaftliche Vorteilhaftigkeit von RPA entsteht vor allem durch Skalierungseffekte. Sobald ein Bot entwickelt wurde, kann er vielfach eingesetzt und vergleichsweise leicht auf weitere Prozesse übertragen werden. Gleichzeitig entstehen laufende Kosten für Wartung, Monitoring und Anpassung an sich verändernde Systeme @Wewerka2020UserAcceptanceRPA;@Lacity2021RPA. Die Literatur macht deutlich, dass RPA keinen ineffizienten Prozess per se verbessert, sondern dessen Ausführung lediglich beschleunigt. Vor der Einführung ist daher eine kritische Prozessanalyse erforderlich.
== 5.3 Auswirkungen auf Mitarbeitende
=== 5.3.1 Motivation, Autonomie und Arbeitszufriedenheit
Die Auswirkungen von RPA auf die Arbeitszufriedenheit sind ambivalent. Zahlreiche Studien berichten, dass Mitarbeitende die Entlastung von monotonen Tätigkeiten positiv bewerten. Die freiwerdende Zeit kann für anspruchsvollere und kreativere Aufgaben genutzt werden, was wiederum zu höherer wahrgenommener Sinnhaftigkeit führen kann. Gleichzeitig bestehen Unsicherheiten hinsichtlich des Einflusses von RPA auf Autonomie und Arbeitsplatzsicherheit. Wo Einbindung und Kommunikation unzureichend sind, werden Rationalisierungsängste verstärkt.
=== 5.3.2 Veränderung von Rollen und Tätigkeiten
RPA führt in vielen Organisationen zu einer Neuverteilung von Aufgaben. Es entstehen neue Rollenprofile, beispielsweise im Bereich der Prozessüberwachung und -gestaltung. Dadurch verändert sich das Kompetenzprofil der Mitarbeitenden. Fachwissen bleibt weiterhin bedeutsam, wird jedoch zunehmend mit IT-bezogenen Fähigkeiten kombiniert @Lacity2021RPA;@Siderska2020RPA. Studien zeigen, dass diese Entwicklung vor allem dann positiv verläuft, wenn Qualifizierungsangebote bereitgestellt werden.
=== 5.3.3 Belastung, Stressfaktoren und Akzeptanz
Neben positiven Effekten werden auch Belastungen beschrieben. Diese ergeben sich etwa aus einer erhöhten Prozessgeschwindigkeit oder aus der Verantwortung für korrektes Bot-Verhalten. Mitarbeitende empfinden die Einführung insbesondere dann als belastend, wenn sie kaum Einfluss auf den Veränderungsprozess haben. Akzeptanz entsteht vor allem dort, wo Transparenz herrscht und die Technologie als unterstützendes Werkzeug erlebt wird @Venkatesh2003UTAUT.
=== 5.3.4 Unterschiede zwischen Kern- und Supportprozessen
Die stärksten Effekte lassen sich in Supportprozessen beobachten, die durch hohe Standardisierung gekennzeichnet sind. In Kernprozessen bleibt menschliche Expertise dagegen unverzichtbar @RPAScientificAndIndustrialMapping;@Nielsen2023RPABenefits. RPA ergänzt hier die Arbeit, anstatt sie zu ersetzen. Dadurch ergibt sich eine unterschiedliche Bedeutung der Technologie je nach Prozessart.

#pagebreak()
= 6 Diskussion

== 6.1 Interpretation der Ergebnisse im Theoriekontext
Die Ergebnisse bestätigen zentrale Annahmen der Prozess- und Effizienztheorie, wonach Standardisierung und Regelgebundenheit wesentliche Treiber für Leistungssteigerungen sind. Technologische Veränderungen können sich sowohl positiv als auch negativ auf die Arbeitszufriedenheit auswirken. Genau diese ambivalente Wirkung wird auch von motivationstheoretischen Ansätzen beschrieben. Die Verlagerung von monotonen Aufgaben auf komplexere analytische Tätigkeiten, fördert die Akzeptanz gegenüber RPA deutlich. @Davis1989TAM.
== 6.2 Zielkonflikte zwischen Qualität, Effizienz und Mitarbeiterperspektive
Die Analyse macht klar, dass zwischen den Zielgrößen Effizienz, Qualität und Mitarbeiterzufriedenheit Spannungsfelder bestehen. Effizienzsteigerung geht nicht automatisch mit Qualitätsverbesserung einher und kann unter ungünstigen Bedingungen sogar zu höheren Belastungen führen. Erfolgreiche RPA-Einführungen balancieren ökonomische und arbeitsbezogene Ziele aus, anstatt sie gegeneinander auszuspielen.
== 6.3 Einordnung in den aktuellen Forschungsstand
Die vorliegenden Ergebnisse bestätigen die Tendenz bisheriger Forschung, differenzieren sie jedoch insofern, als sie technische und menschliche Komponenten integrieren. Besonders deutlich wird die Kontextabhängigkeit der Effekte. RPA ist kein generisches Instrument, sondern wirkt unterschiedlich je nach Prozessreife, Organisationskultur und Einführungsstrategie.
== 6.4 Kritische Reflexion und Limitationen
Die Untersuchung basiert ausschließlich auf vorhandener Literatur. Die Ergebnisse sind daher abhängig von Qualität und Schwerpunktsetzung der analysierten Studien. Zudem liegen nur wenige langfristige Untersuchungen vor. Kausale Zusammenhänge können deshalb lediglich eingeschränkt abgeleitet werden.

= 7 Handlungsmöglichkeiten für Unternehmen

Unternehmen sollten RPA nicht isoliert als technische Lösung betrachten, sondern als Bestandteil eines umfassenden organisatorischen Veränderungsprozesses. Vor der Implementierung empfiehlt sich eine sorgfältige Analyse der Prozessreife sowie der Ausnahmequote. Nur klar strukturierte Prozesse eignen sich unmittelbar für die Automatisierung.

Darüber hinaus zeigt die Analyse, dass eine frühzeitige Einbindung der Mitarbeitenden entscheidend für die Akzeptanz ist. RPA sollte als Unterstützung und nicht als Ersatz kommuniziert werden. Qualifizierungsprogramme tragen wesentlich dazu bei, technologische Unsicherheiten abzubauen und neue Kompetenzanforderungen zu erfüllen.

Ebenfalls zentral ist der Aufbau einer Governance-Struktur. Dazu zählen klare Verantwortlichkeiten, kontinuierliches Monitoring sowie eine systematische Weiterentwicklung der automatisierten Prozesse. RPA entfaltet seine volle Wirkung vor allem dann, wenn es dauerhaft gepflegt und an sich wandelnde Rahmenbedingungen angepasst wird @Lacity2021RPA.

Langfristiger Erfolg entsteht, wenn Automatisierung strategisch verankert wird und nicht nur punktuell angewendet wird. Entscheidend ist ein ganzheitlicher Blick auf Technik, Prozessorganisation und Mensch-Technik-Interaktion.

= 8 Fazit und Ausblick

== 8.1 Beantwortung der Forschungsfrage
Die Analyse zeigt, dass der Einsatz von RPA einen deutlichen Einfluss auf digitale Geschäftsprozesse hat. Prozessqualität und Effizienz können insbesondere in standardisierten und strukturierten Abläufen signifikant verbessert werden. Die Auswirkungen auf Mitarbeiter sind jedoch ambivalent und stark kontextabhängig. RPA erweist sich damit als wirkungsvolles, aber sensibles Gestaltungsinstrument der digitalen Transformation @EffectsRPA @Nielsen2023RPABenefits.
== 8.2 Implikationen für Forschung und Praxis
Für die Praxis bedeutet dies, dass Automatisierung nur dann nachhaltig erfolgreich ist, wenn neben technischen und ökonomischen Zielen auch arbeitswissenschaftliche Aspekte berücksichtigt werden. Für die Forschung ergibt sich ein Bedarf an integrierten, theoriegeleiteten Studien, die sowohl objektive Prozesskennzahlen als auch subjektive Wahrnehmungen systematisch erfassen.
== 8.3 Ausblick: Intelligent Automation und KI-Integration
Mit der zunehmenden Integration von KI-Technologien entwickelt sich RPA perspektivisch zu „Intelligent Automation“. Dadurch erweitert sich das Einsatzspektrum auf weniger strukturierte Prozesse. Gleichzeitig steigen jedoch die Anforderungen an Governance, Transparenz und Qualifizierung. Der Mensch wird künftig weniger operativ ausführen, sondern zunehmend koordinieren, entscheiden und verantworten @Syed2020IPA.